<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bounded Nonlinear Reconstruction – Latent Dynamics &amp; Geometry</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-445b8638c3d06994fee0907d791121c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Latent Dynamics &amp; Geometry</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../knowledge/concepts/index.html"> 
<span class="menu-text">Concepts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../knowledge/methods/index.html"> 
<span class="menu-text">Methods</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../knowledge/math/index.html"> 
<span class="menu-text">Math</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../knowledge/papers/index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../toy-models/index.html"> 
<span class="menu-text">Toy Models</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../research-questions/index.html"> 
<span class="menu-text">Research Questions</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../benchmarks/index.html"> 
<span class="menu-text">Benchmarks</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AbelZheng/latent-dynamics-geometry-public"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/AbelZheng/latent-dynamics-geometry-public/discussions"> 
<span class="menu-text">Discussions</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#bounded-nonlinear-reconstruction" id="toc-bounded-nonlinear-reconstruction" class="nav-link active" data-scroll-target="#bounded-nonlinear-reconstruction">Bounded Nonlinear Reconstruction</a>
  <ul class="collapse">
  <li><a href="#question" id="toc-question" class="nav-link" data-scroll-target="#question">Question</a></li>
  <li><a href="#ground-truth" id="toc-ground-truth" class="nav-link" data-scroll-target="#ground-truth">Ground truth</a></li>
  <li><a href="#generative-model" id="toc-generative-model" class="nav-link" data-scroll-target="#generative-model">Generative model</a></li>
  <li><a href="#parameters" id="toc-parameters" class="nav-link" data-scroll-target="#parameters">Parameters</a></li>
  <li><a href="#simulation" id="toc-simulation" class="nav-link" data-scroll-target="#simulation">Simulation</a>
  <ul class="collapse">
  <li><a href="#nominal-curved-condition" id="toc-nominal-curved-condition" class="nav-link" data-scroll-target="#nominal-curved-condition">Nominal curved condition</a></li>
  <li><a href="#full-dimensional-gaussian" id="toc-full-dimensional-gaussian" class="nav-link" data-scroll-target="#full-dimensional-gaussian">Full-dimensional Gaussian</a></li>
  <li><a href="#high-variance-nuisance" id="toc-high-variance-nuisance" class="nav-link" data-scroll-target="#high-variance-nuisance">High-variance nuisance</a></li>
  <li><a href="#few-samplehigh-capacity" id="toc-few-samplehigh-capacity" class="nav-link" data-scroll-target="#few-samplehigh-capacity">Few-sample/high-capacity</a></li>
  <li><a href="#shifted-range" id="toc-shifted-range" class="nav-link" data-scroll-target="#shifted-range">Shifted range</a></li>
  </ul></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization">Visualization</a></li>
  <li><a href="#expected-behavior" id="toc-expected-behavior" class="nav-link" data-scroll-target="#expected-behavior">Expected behavior</a></li>
  <li><a href="#parameter-manipulations" id="toc-parameter-manipulations" class="nav-link" data-scroll-target="#parameter-manipulations">Parameter manipulations</a></li>
  <li><a href="#sanity-checks" id="toc-sanity-checks" class="nav-link" data-scroll-target="#sanity-checks">Sanity checks</a></li>
  <li><a href="#failure-cases" id="toc-failure-cases" class="nav-link" data-scroll-target="#failure-cases">Failure cases</a></li>
  <li><a href="#recovery-task" id="toc-recovery-task" class="nav-link" data-scroll-target="#recovery-task">Recovery task</a>
  <ul class="collapse">
  <li><a href="#mean-and-pca" id="toc-mean-and-pca" class="nav-link" data-scroll-target="#mean-and-pca">Mean and PCA</a></li>
  <li><a href="#linear-autoencoder" id="toc-linear-autoencoder" class="nav-link" data-scroll-target="#linear-autoencoder">Linear autoencoder</a></li>
  <li><a href="#nonlinear-autoencoder" id="toc-nonlinear-autoencoder" class="nav-link" data-scroll-target="#nonlinear-autoencoder">Nonlinear autoencoder</a></li>
  <li><a href="#frozen-random-encoder" id="toc-frozen-random-encoder" class="nav-link" data-scroll-target="#frozen-random-encoder">Frozen random encoder</a></li>
  </ul></li>
  <li><a href="#candidate-analysis-methods" id="toc-candidate-analysis-methods" class="nav-link" data-scroll-target="#candidate-analysis-methods">Candidate analysis methods</a></li>
  <li><a href="#evaluation" id="toc-evaluation" class="nav-link" data-scroll-target="#evaluation">Evaluation</a>
  <ul class="collapse">
  <li><a href="#empirical-results" id="toc-empirical-results" class="nav-link" data-scroll-target="#empirical-results">Empirical results</a></li>
  </ul></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#what-this-toy-model-does-not-establish" id="toc-what-this-toy-model-does-not-establish" class="nav-link" data-scroll-target="#what-this-toy-model-does-not-establish">What this toy model does NOT establish</a></li>
  <li><a href="#extensions-to-real-data" id="toc-extensions-to-real-data" class="nav-link" data-scroll-target="#extensions-to-real-data">Extensions to real data</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a>
  <ul class="collapse">
  <li><a href="#evidence-inspected" id="toc-evidence-inspected" class="nav-link" data-scroll-target="#evidence-inspected">Evidence inspected</a></li>
  </ul></li>
  <li><a href="#maturity-checklist" id="toc-maturity-checklist" class="nav-link" data-scroll-target="#maturity-checklist">Maturity checklist</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Bounded Nonlinear Reconstruction</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="bounded-nonlinear-reconstruction" class="level1">
<h1>Bounded Nonlinear Reconstruction</h1>
<p>This L1/stable Candidate G Toy Model asks whether one fixed small nonlinear autoencoder improves held-out reconstruction over rank-matched linear methods on a known curved simulator, while controls expose full-dimensional data, nuisance variance, finite-sample capacity, and extrapolation. Numerical values are deterministic outputs under master seed <code>20260819</code>; they are conditional on the declared architecture, optimizer, preprocessing, splits, and loss.</p>
<p><strong>Assumed background:</strong> centered/scaled PCA, deterministic feed-forward networks, reverse-mode differentiation, full-batch Adam, and leakage-safe train/validation/test evaluation.</p>
<section id="question" class="level2">
<h2 class="anchored" data-anchor-id="question">Question</h2>
<p>For observations generated from one scalar through a fixed curved map into six features:</p>
<ol type="1">
<li>does a one-coordinate nonlinear bottleneck improve held-out MSE over the training mean, rank-one PCA, and a trained linear autoencoder in the identical standardized metric;</li>
<li>does learning the encoder improve on a frozen random nonlinear encoder with a trained decoder;</li>
<li>are reconstruction, code activity, and checkpoint choice stable across five predeclared seeds;</li>
<li>how do results change for full-dimensional Gaussian data, independent high-variance nuisance features, few samples with a larger architecture, and shifted test support; and</li>
<li>which conclusions remain strictly about reconstruction rather than manifold structure, intrinsic dimension, unique coordinates, representation, or mechanism?</li>
</ol>
</section>
<section id="ground-truth" class="level2">
<h2 class="anchored" data-anchor-id="ground-truth">Ground truth</h2>
<p>The ambient dimension is <span class="math inline">\(p=6\)</span> and the scoring-only parameter is <span class="math inline">\(s\)</span>. For curved conditions,</p>
<p><span class="math display">\[
g(s)=
\begin{pmatrix}
s\\ s^2\\0.35\sin(2s)\\0.2s^3\\\cos(s)-\sin(1.5)/1.5\\0.4\sin(3s)
\end{pmatrix},
\]</span></p>
<p>and</p>
<p><span class="math display">\[
x=g(s)+\epsilon,\qquad \epsilon\sim\mathcal N(0,0.06^2I_6).
\]</span></p>
<p>Nominal train, validation, and test values use <span class="math inline">\(s\sim\operatorname{Uniform}[-1.5,1.5]\)</span>. The shifted-range test draws both signs with <span class="math inline">\(|s|\sim\operatorname{Uniform}[1.5,2.4]\)</span>, while its train and validation samples remain in range. The implementation retains <span class="math inline">\(s\)</span> and <span class="math inline">\(g(s)\)</span> for simulation scoring only; neither is a training target.</p>
<p>The full-dimensional control draws from a full-rank Gaussian whose population mean and covariance exactly match the nominal curved <strong>observable</strong> distribution, including <span class="math inline">\(0.06^2I_6\)</span> noise. A fixed 256-node Gauss–Legendre rule on <span class="math inline">\([-1.5,1.5]\)</span> computes those moments. The resulting covariance eigenvalues are approximately</p>
<p><span class="math display">\[
(0.85225,0.53472,0.10844,0.00563,0.00378,0.00360),
\]</span></p>
<p>so the Gaussian remains full rank while having no scalar generator truth. Executable target-moment discrepancies are zero; finite sampled splits are permitted ordinary sampling deviations. A one-dimensional bottleneck applied to this condition is imposed compression, not a dimension estimate.</p>
</section>
<section id="generative-model" class="level2">
<h2 class="anchored" data-anchor-id="generative-model">Generative model</h2>
<p>Independent split sizes are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Condition</th>
<th style="text-align: right;">Train</th>
<th style="text-align: right;">Validation</th>
<th style="text-align: right;">Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nominal curved</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">240</td>
</tr>
<tr class="even">
<td>full-dimensional Gaussian</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">240</td>
</tr>
<tr class="odd">
<td>high-variance nuisance</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">240</td>
</tr>
<tr class="even">
<td>few-sample/high-capacity</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">240</td>
</tr>
<tr class="odd">
<td>shifted range</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">240</td>
</tr>
</tbody>
</table>
<p>For the nuisance condition, independent Gaussian noise with standard deviation 2.5 is added to features 5–6 after the curved signal and ordinary noise. This separates standardized objective performance from original-unit error dominated by scientifically uninformative variance.</p>
<p>All streams use <code>Generator(PCG64(SeedSequence(words)))</code>. Generation, training-only standardization, initialization, optimization, validation checkpointing, seed selection, scoring, plotting, and verification are separate functions.</p>
</section>
<section id="parameters" class="level2">
<h2 class="anchored" data-anchor-id="parameters">Parameters</h2>
<p>Every condition uses a training-fitted feature mean and population-divisor standard deviation. All deterministic methods optimize or are scored in the same transformed-coordinate Euclidean MSE, and reconstructions are also returned to original units.</p>
<p>The bottleneck width is one. There are no skip connections, stochastic layers, denoising, sparsity, or output nonlinearities.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Family</th>
<th>Architecture</th>
<th style="text-align: right;">Trainable parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Trained linear AE</td>
<td><span class="math inline">\(6\to1\to6\)</span></td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td>Small nonlinear AE</td>
<td><span class="math inline">\(6\to8\to1\to8\to6\)</span></td>
<td style="text-align: right;">135</td>
</tr>
<tr class="odd">
<td>Frozen random encoder, ordinary conditions</td>
<td>frozen <span class="math inline">\(6\to8\to1\)</span>, trained <span class="math inline">\(1\to8\to6\)</span></td>
<td style="text-align: right;">70 trained, 65 frozen, 135 total</td>
</tr>
<tr class="even">
<td>Few-sample nonlinear AE</td>
<td><span class="math inline">\(6\to32\to1\to32\to6\)</span></td>
<td style="text-align: right;">519 trainable</td>
</tr>
<tr class="odd">
<td>Few-sample frozen encoder</td>
<td>frozen <span class="math inline">\(6\to32\to1\)</span>, trained <span class="math inline">\(1\to32\to6\)</span></td>
<td style="text-align: right;">262 trained, 257 frozen, 519 total</td>
</tr>
</tbody>
</table>
<p>Five predeclared seeds are <code>0,1,2,3,4</code>. Initialization is family-specific and recorded in the manifest:</p>
<ul>
<li>the linear AE is a <strong>PCA-warm-started optimization control</strong>: encoder/decoder weights begin at the training rank-one PCA direction plus seed-specific <span class="math inline">\(\mathcal N(0,0.02^2)\)</span> perturbations, with zero biases;</li>
<li>nonlinear AE weights use independent centered Normal draws with Glorot-like scale <span class="math inline">\(\sqrt{2/(fan_{in}+fan_{out})}\)</span> and zero biases; and</li>
<li>the frozen encoder uses fixed centered Normal weights with variances <span class="math inline">\(1/6\)</span> and <span class="math inline">\(1/H\)</span> and small random encoder biases, while its trainable decoder uses Glorot-like centered Normal weights and zero decoder biases.</li>
</ul>
<p>Training uses manual full-batch Adam with <span class="math inline">\((\beta_1,\beta_2,\epsilon)=(0.9,0.999,10^{-8})\)</span>, no weight decay, and linear output. Learning rates are 0.025 for linear AE, 0.012 for nonlinear AE, and 0.015 for the frozen-encoder decoder. Each family has at most 900 epochs and patience 120. Validation selects the earliest strict minimum per seed, then the seed with minimum validation loss and lower-seed tie breaking. Test data never select an epoch or seed.</p>
<p>These are LDG design choices, not literature-supplied optimal settings.</p>
</section>
<section id="simulation" class="level2">
<h2 class="anchored" data-anchor-id="simulation">Simulation</h2>
<section id="nominal-curved-condition" class="level3">
<h3 class="anchored" data-anchor-id="nominal-curved-condition">Nominal curved condition</h3>
<p>This is the primary nonlinear-reconstruction condition. Generator-code correlations are permitted only as simulation diagnostics after fitting.</p>
</section>
<section id="full-dimensional-gaussian" class="level3">
<h3 class="anchored" data-anchor-id="full-dimensional-gaussian">Full-dimensional Gaussian</h3>
<p>The moment-matched full-rank Gaussian has no <span class="math inline">\(s\)</span> or noiseless one-dimensional map. Code–<span class="math inline">\(s\)</span>, monotonicity, and generator-recovery rows are omitted. Any nonlinear reconstruction advantage remains a compression result after controlling first and second population moments.</p>
</section>
<section id="high-variance-nuisance" class="level3">
<h3 class="anchored" data-anchor-id="high-variance-nuisance">High-variance nuisance</h3>
<p>The first four features retain curved signal; the final two receive large independent nuisance variance. Report structural-feature and nuisance-feature MSE separately. Neither standardized nor original-unit MSE is declared universally correct.</p>
</section>
<section id="few-samplehigh-capacity" class="level3">
<h3 class="anchored" data-anchor-id="few-samplehigh-capacity">Few-sample/high-capacity</h3>
<p>Only 40 rows train both the 519-parameter nonlinear model and the architecture-matched width-32 frozen-encoder control with 257 frozen and 262 trained decoder parameters. Report complete train, validation, and test errors and seed variation. In this realized dataset validation selection prevents a dramatic memorization gap; this negative control remains informative even though the expected failure is not forced.</p>
</section>
<section id="shifted-range" class="level3">
<h3 class="anchored" data-anchor-id="shifted-range">Shifted range</h3>
<p>The model and standardizer are fitted only in range and applied unchanged outside training support. This is extrapolation, not another validation split.</p>
</section>
</section>
<section id="visualization" class="level2">
<h2 class="anchored" data-anchor-id="visualization">Visualization</h2>
<p>The single composite <code>summary.png</code> shows bounded nominal reconstructions, selected test reconstruction metrics across conditions, selected loss histories, and code-versus-<span class="math inline">\(s\)</span> diagnostics for nominal and shifted tests.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="artifacts/bounded-nonlinear-reconstruction/summary.png" class="img-fluid figure-img"></p>
<figcaption>Bounded nonlinear reconstruction diagnostic</figcaption>
</figure>
</div>
<p>The figure is diagnostic only. All methods use training-only standardization; validation selects checkpoints/seeds; test data do not select models. Code plots are simulation-side diagnostics, not manifold or intrinsic-coordinate evidence.</p>
</section>
<section id="expected-behavior" class="level2">
<h2 class="anchored" data-anchor-id="expected-behavior">Expected behavior</h2>
<ul>
<li>Rank-one PCA is the analytic linear reconstruction reference. A well-trained linear AE should approach its reconstructed subspace and loss <span class="citation" data-cites="BourlardKamp1988 BaldiHornik1989">(<a href="#ref-BourlardKamp1988" role="doc-biblioref">Bourlard and Kamp 1988</a>; <a href="#ref-BaldiHornik1989" role="doc-biblioref">Baldi and Hornik 1989</a>)</span>.</li>
<li>A small nonlinear AE can improve interpolation on the curved generator without proving that an arbitrary dataset is one-dimensional or manifold-valued.</li>
<li>Frozen random nonlinear features can reconstruct some structure, so their full seed distribution is necessary before crediting learned encoding.</li>
<li>Full-dimensional Gaussian data provide no valid scalar-generator recovery claim even if a flexible model improves MSE.</li>
<li>Standardization can prevent nuisance features from dominating the optimized metric while original-unit error remains nuisance-dominated.</li>
<li>Out-of-range reconstruction and code ordering may degrade sharply despite good in-range validation.</li>
<li>A larger network with few samples can overfit, but predeclared validation stopping may also prevent the intended dramatic failure. Negative controls are reported, not tuned to guarantee a story.</li>
</ul>
</section>
<section id="parameter-manipulations" class="level2">
<h2 class="anchored" data-anchor-id="parameter-manipulations">Parameter manipulations</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th>Changed assumption</th>
<th>Diagnostic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>nominal_curved</code></td>
<td>none</td>
<td>bounded nonlinear held-out gain</td>
</tr>
<tr class="even">
<td><code>full_dimensional_gaussian</code></td>
<td>no scalar curved generator</td>
<td>imposed one-code compression</td>
</tr>
<tr class="odd">
<td><code>high_variance_nuisance</code></td>
<td>large independent variance in features 5–6</td>
<td>structural/nuisance and metric dependence</td>
</tr>
<tr class="even">
<td><code>few_sample_high_capacity</code></td>
<td>40 training rows and width 32</td>
<td>capacity, seed, and generalization gap</td>
</tr>
<tr class="odd">
<td><code>shifted_range</code></td>
<td>test support outside training range</td>
<td>extrapolation and code ordering</td>
</tr>
</tbody>
</table>
<p>No condition, architecture, seed set, optimizer budget, or noise magnitude is retuned from test results.</p>
</section>
<section id="sanity-checks" class="level2">
<h2 class="anchored" data-anchor-id="sanity-checks">Sanity checks</h2>
<p>The verifier checks:</p>
<ol type="1">
<li>exact split regeneration for observations, <span class="math inline">\(s\)</span>, and noiseless curves;</li>
<li>test-observation poisoning leaves standardization, all candidates, checkpoint histories, and selected seeds unchanged;</li>
<li>poisoning every <span class="math inline">\(s\)</span> and noiseless-truth array leaves all observation-only fits and reconstructions unchanged;</li>
<li>PCA and the analytic linear reconstruction are identical;</li>
<li>selected trained-linear-AE composite projector, subspace angle, and training MSE approach PCA within declared tolerances; failure would be labelled optimization failure;</li>
<li>centered finite-difference gradients for linear, nonlinear, and frozen-decoder networks agree with analytic backpropagation;</li>
<li>validation checkpoint losses and earliest-minimum epochs recompute exactly;</li>
<li>validation seed selection replays exactly;</li>
<li>repeated full-batch Adam training is deterministic;</li>
<li>frozen encoder parameters never change;</li>
<li>bottleneck shape is exactly <span class="math inline">\(n\times1\)</span>, parameter counts match architecture, and no skip path exists;</li>
<li>all losses, parameters, codes, reconstructions, and metric values are finite;</li>
<li>metric rows have the exact schema, nonempty labels, finite values, and unique composite keys; and</li>
<li>a clean temporary regeneration produces byte-identical generated artifacts.</li>
</ol>
<p>These checks support implementation integrity, not manifold or mechanism claims.</p>
</section>
<section id="failure-cases" class="level2">
<h2 class="anchored" data-anchor-id="failure-cases">Failure cases</h2>
<ul>
<li><strong>Different metrics for PCA and AE:</strong> preprocessing or test-fitted scaling makes comparison invalid.</li>
<li><strong>Poor linear optimization called nonlinear gain:</strong> analytic PCA remains the authoritative linear baseline.</li>
<li><strong>Best test seed selection:</strong> all checkpoint and seed choices must use validation only.</li>
<li><strong>Low training error called recovery:</strong> the full train/validation/test gap must remain visible.</li>
<li><strong>Frozen encoder silently updated:</strong> encoder immutability is executable-checked.</li>
<li><strong>Dead or collapsed code hidden:</strong> code variance, range, and collision diagnostics are reported.</li>
<li><strong>Nuisance reconstruction called scientific signal:</strong> structural and nuisance errors remain separate.</li>
<li><strong>Full Gaussian called one-dimensional:</strong> no scalar truth rows exist for that condition.</li>
<li><strong>In-range interpolation generalized to shifted support:</strong> shifted metrics are explicitly extrapolation.</li>
<li><strong>Code correlation called coordinate identification:</strong> correlation with <span class="math inline">\(s\)</span> is scoring-only and does not identify a unique code.</li>
<li><strong>One active bottleneck called intrinsic dimension:</strong> bottleneck width is fixed by the analyst.</li>
</ul>
</section>
<section id="recovery-task" class="level2">
<h2 class="anchored" data-anchor-id="recovery-task">Recovery task</h2>
<section id="mean-and-pca" class="level3">
<h3 class="anchored" data-anchor-id="mean-and-pca">Mean and PCA</h3>
<p>The transformed training mean is zero. Rank-one PCA fits the leading right singular vector and applies its orthogonal projector.</p>
</section>
<section id="linear-autoencoder" class="level3">
<h3 class="anchored" data-anchor-id="linear-autoencoder">Linear autoencoder</h3>
<p>The trainable linear encoder and decoder are optimized under the same MSE. The composite map, not individual factors, is compared with the PCA projector.</p>
</section>
<section id="nonlinear-autoencoder" class="level3">
<h3 class="anchored" data-anchor-id="nonlinear-autoencoder">Nonlinear autoencoder</h3>
<p>For hidden width <span class="math inline">\(h\)</span>, the encoder is <span class="math inline">\(\tanh(W_eu+b_e)\)</span> followed by one linear code; the decoder applies one tanh hidden layer and a linear output. All trainable parameters use the fixed optimizer protocol.</p>
</section>
<section id="frozen-random-encoder" class="level3">
<h3 class="anchored" data-anchor-id="frozen-random-encoder">Frozen random encoder</h3>
<p>The nonlinear encoder is initialized and copied before training. Only the decoder is optimized. This controls whether generic frozen nonlinear features are sufficient.</p>
</section>
</section>
<section id="candidate-analysis-methods" class="level2">
<h2 class="anchored" data-anchor-id="candidate-analysis-methods">Candidate analysis methods</h2>
<ol type="1">
<li>training mean;</li>
<li>rank-one PCA;</li>
<li>trained rank-one linear AE;</li>
<li>fixed small nonlinear tanh AE;</li>
<li>frozen random tanh encoder with trained decoder; and</li>
<li>the larger nonlinear architecture in the few-sample stress.</li>
</ol>
<p>No method receives <span class="math inline">\(s\)</span>, noiseless <span class="math inline">\(g(s)\)</span>, test preprocessing statistics, or test-selected epochs.</p>
</section>
<section id="evaluation" class="level2">
<h2 class="anchored" data-anchor-id="evaluation">Evaluation</h2>
<p><code>metrics.csv</code> contains:</p>
<pre class="text"><code>split,condition,preprocessing,method,seed,selection,target,metric,value</code></pre>
<p>It reports transformed and original-unit MSE by split, per-feature MSE, train–test gaps, parameter counts, selected seeds/epochs, all seed validation records, code mean/variance/range and collapse/dead indicators, and condition-specific structural/nuisance or generator diagnostics.</p>
<section id="empirical-results" class="level3">
<h3 class="anchored" data-anchor-id="empirical-results">Empirical results</h3>
<p>Selected-model test original-unit MSE:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th style="text-align: right;">PCA</th>
<th style="text-align: right;">Linear AE</th>
<th style="text-align: right;">Nonlinear AE</th>
<th style="text-align: right;">Frozen encoder</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nominal curved</td>
<td style="text-align: right;">0.1082</td>
<td style="text-align: right;">0.1085</td>
<td style="text-align: right;"><strong>0.00958</strong></td>
<td style="text-align: right;">0.1288</td>
</tr>
<tr class="even">
<td>Moment-matched full-dimensional Gaussian</td>
<td style="text-align: right;">0.11245</td>
<td style="text-align: right;">0.11213</td>
<td style="text-align: right;">0.11318</td>
<td style="text-align: right;">0.15416</td>
</tr>
<tr class="odd">
<td>High-variance nuisance</td>
<td style="text-align: right;">2.0780</td>
<td style="text-align: right;">2.0854</td>
<td style="text-align: right;">1.8351</td>
<td style="text-align: right;"><strong>1.7160</strong></td>
</tr>
<tr class="even">
<td>Few-sample/high-capacity</td>
<td style="text-align: right;">0.1177</td>
<td style="text-align: right;">0.1175</td>
<td style="text-align: right;"><strong>0.00525</strong></td>
<td style="text-align: right;">0.0389</td>
</tr>
<tr class="odd">
<td>Shifted range</td>
<td style="text-align: right;">2.1218</td>
<td style="text-align: right;">2.1228</td>
<td style="text-align: right;"><strong>0.9146</strong></td>
<td style="text-align: right;">2.7996</td>
</tr>
</tbody>
</table>
<p>The nominal nonlinear code has absolute Pearson/Spearman correlation 0.901/0.846 with scoring-only <span class="math inline">\(s\)</span>. The reported collision diagnostic is a nonstandard LDG threshold check: among all <span class="math inline">\(n(n-1)/2=28{,}680\)</span> test pairs, define a close-code denominator by <span class="math inline">\(|\Delta z|\le0.05\)</span> of the observed code range; a collision additionally requires <span class="math inline">\(|\Delta s|&gt;0.5\)</span>. The selected nominal model has 4,135 close-code pairs and 39 collisions, fraction 0.00943. These thresholds and values do not establish injectivity or unique coordinates. Under nuisance variance, nonlinear structural-feature MSE is 0.0125 while nuisance-feature MSE is 5.48, showing why aggregate original-unit loss can obscure scientific structure. The few-sample nonlinear train/test MSE is 0.00321/0.00525: the larger network fits well but the predeclared validation protocol avoids a dramatic memorization failure. Shifted nonlinear test MSE is computed with the exact nominal train/validation bundles, standardizer, candidate histories, checkpoints, selected seeds, and fitted models; only the exterior-support test bundle differs. Its selected code has 13,390 close-code pairs and 1,852 collisions, fraction 0.1383, exposing extrapolation limits.</p>
<p>The moment-matched Gaussian nonlinear result is slightly worse than PCA/linear AE in this realization and is not evidence for one-dimensional structure. Seed variability remains in the full metric table and selection is validation-only.</p>
</section>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<p>The nominal result establishes only that this selected finite nonlinear network reconstructs held-out samples from this curved simulator better than rank-one PCA under the declared standardized MSE. The full-dimensional, nuisance, few-sample, frozen-feature, and shifted controls show that reconstruction gains can coexist with absent one-dimensional truth, irrelevant variance, capacity sensitivity, useful random features, or poor extrapolation.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="What this does NOT imply">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>What this does NOT imply
</div>
</div>
<div class="callout-body-container callout-body">
<p>Low reconstruction error, an active one-dimensional code, or correlation with a known simulator parameter does not prove a manifold, intrinsic dimension, unique latent coordinate, representation, causal variable, dynamics, or mechanism.</p>
</div>
</div>
</section>
<section id="what-this-toy-model-does-not-establish" class="level2">
<h2 class="anchored" data-anchor-id="what-this-toy-model-does-not-establish">What this toy model does NOT establish</h2>
<ul>
<li>a model-free intrinsic dimension;</li>
<li>a smooth or injective manifold chart;</li>
<li>unique encoder/decoder parameters or code axes;</li>
<li>a probability model, posterior, or uncertainty distribution;</li>
<li>dynamics, temporal order, a vector field, or state transition;</li>
<li>a causal, biological, or physical mechanism;</li>
<li>universal nonlinear superiority over PCA; or</li>
<li>reliable extrapolation outside the tested range.</li>
</ul>
</section>
<section id="extensions-to-real-data" class="level2">
<h2 class="anchored" data-anchor-id="extensions-to-real-data">Extensions to real data</h2>
<p>Real-data use must define independent units, feature scaling, missingness, architecture/capacity search, nested validation, subject/session shift, nuisance features, and the scientific cost of per-feature errors. A reconstruction baseline should be accompanied by PCA, random-feature, capacity, seed, leakage, and distribution-shift checks. Codes should not receive semantic or mechanistic names from geometry alone.</p>
</section>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">Reproducibility</h2>
<p>The bounded artifact set is:</p>
<pre class="text"><code>toy-models/bounded-nonlinear-reconstruction.py
toy-models/artifacts/bounded-nonlinear-reconstruction/manifest.json
toy-models/artifacts/bounded-nonlinear-reconstruction/metrics.csv
toy-models/artifacts/bounded-nonlinear-reconstruction/diagnostics.json
toy-models/artifacts/bounded-nonlinear-reconstruction/summary.png</code></pre>
<p>The bundled-runtime command is:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">/Users/bytedance/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3</span> toy-models/bounded-nonlinear-reconstruction.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Default execution generates and verifies, including temporary byte-identical regeneration. The manifest records generator and split contracts, preprocessing, architectures, parameter counts, seeds, optimizer/checkpoint rules, applicability, runtime, commands, and hashes.</p>
<section id="evidence-inspected" class="level3">
<h3 class="anchored" data-anchor-id="evidence-inspected">Evidence inspected</h3>
<ul>
<li><strong>Bourlard and Kamp (1988):</strong> the complete four-page article was inspected for the SVD solution, centering/bias treatment, linear hidden-unit relationship, small-signal sigmoid discussion, experiment, and conclusion <span class="citation" data-cites="BourlardKamp1988">(<a href="#ref-BourlardKamp1988" role="doc-biblioref">Bourlard and Kamp 1988</a>)</span>.</li>
<li><strong>Baldi and Hornik (1989):</strong> the complete six-page article was inspected for the squared-error landscape, principal-subspace optimum, factor nonuniqueness, boundary cases, algorithm discussion, and appendices <span class="citation" data-cites="BaldiHornik1989">(<a href="#ref-BaldiHornik1989" role="doc-biblioref">Baldi and Hornik 1989</a>)</span>.</li>
<li><strong>Kramer (1991):</strong> the nonlinear auto-associative architecture, reconstruction objective, capacity/overfitting discussion, training procedure, examples, and conclusion were inspected; sequential-factor and related-work details were read only at overview depth <span class="citation" data-cites="Kramer1991">(<a href="#ref-Kramer1991" role="doc-biblioref">Kramer 1991</a>)</span>.</li>
<li><strong>Goodfellow, Bengio, and Courville (2016), Chapter 14:</strong> the introduction, undercomplete autoencoders, capacity and copying failures, relevant real-valued/MSE material, manifold-learning interpretation limits, and optimization/generalization discussion were inspected. Excluded autoencoder variants were not inspected equation by equation <span class="citation" data-cites="GoodfellowBengioCourville2016">(<a href="#ref-GoodfellowBengioCourville2016" role="doc-biblioref">Goodfellow et al. 2016, chap. 14</a>)</span>.</li>
</ul>
<p>These sources do not supply this simulator, architecture, seeds, optimizer budgets, thresholds, or artifact format; those are LDG design choices.</p>
</section>
</section>
<section id="maturity-checklist" class="level2">
<h2 class="anchored" data-anchor-id="maturity-checklist">Maturity checklist</h2>
<ul class="task-list">
<li><label><input type="checkbox" checked="">Complete L1/stable Toy Model schema and artifact contract.</label></li>
<li><label><input type="checkbox" checked="">Known curved generator, full-dimensional, nuisance, few-sample, and shift controls are explicit.</label></li>
<li><label><input type="checkbox" checked="">Mean, PCA, linear AE, nonlinear AE, and frozen-encoder comparisons share training-only preprocessing and MSE geometry.</label></li>
<li><label><input type="checkbox" checked="">Architecture, parameter counts, optimizer, budgets, patience, seeds, checkpoints, and selection are fixed.</label></li>
<li><label><input type="checkbox" checked="">Split losses, feature errors, seed distributions, code activity, generator and extrapolation diagnostics are reported.</label></li>
<li><label><input type="checkbox" checked="">Gradient, checkpoint, seed, leakage, PCA/linear, architecture, and deterministic oracles pass.</label></li>
<li><label><input type="checkbox" checked="">Manifold, dimension, coordinate, dynamics, mechanism, representation, and causal overclaims are prohibited.</label></li>
<li><label><input type="checkbox" checked="">Independent scientific review PASS.</label></li>
<li><label><input type="checkbox" checked="">Independent implementation review PASS.</label></li>
<li><label><input type="checkbox" checked="">Repository validation and renders PASS after review.</label></li>
<li><label><input type="checkbox" checked="">Mechanical L1/stable promotion under the recorded review decision.</label></li>
</ul>


<!-- -->


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-BaldiHornik1989" class="csl-entry" role="listitem">
Baldi, Pierre, and Kurt Hornik. 1989. <span>“Neural Networks and Principal Component Analysis: Learning from Examples Without Local Minima.”</span> <em>Neural Networks</em> 2 (1): 53–58. <a href="https://doi.org/10.1016/0893-6080(89)90014-2">https://doi.org/10.1016/0893-6080(89)90014-2</a>.
</div>
<div id="ref-BourlardKamp1988" class="csl-entry" role="listitem">
Bourlard, Hervé, and Yves Kamp. 1988. <span>“Auto-Association by Multilayer Perceptrons and Singular Value Decomposition.”</span> <em>Biological Cybernetics</em> 59 (4–5): 291–94. <a href="https://doi.org/10.1007/BF00332918">https://doi.org/10.1007/BF00332918</a>.
</div>
<div id="ref-GoodfellowBengioCourville2016" class="csl-entry" role="listitem">
Goodfellow, Ian, Yoshua Bengio, and Aaron Courville. 2016. <em>Deep Learning</em>. MIT Press. <a href="https://www.deeplearningbook.org/">https://www.deeplearningbook.org/</a>.
</div>
<div id="ref-Kramer1991" class="csl-entry" role="listitem">
Kramer, Mark A. 1991. <span>“Nonlinear Principal Component Analysis Using Autoassociative Neural Networks.”</span> <em>AIChE Journal</em> 37 (2): 233–43. <a href="https://doi.org/10.1002/aic.690370209">https://doi.org/10.1002/aic.690370209</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/abelzheng\.github\.io\/latent-dynamics-geometry-public\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="preferred_color_scheme">
<input type="hidden" id="giscus-alt-theme" value="preferred_color_scheme">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "AbelZheng/latent-dynamics-geometry-public";
    script.dataset.repoId = "R_kgDOT-VBkw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOT-VBk84DDyEz";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "bottom";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Bounded Nonlinear Reconstruction"</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="an">object_type:</span><span class="co"> toy-model</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="an">maturity:</span><span class="co"> L1</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="an">status:</span><span class="co"> stable</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="an">domain:</span><span class="co"> [dimensionality-reduction, neural-networks, nonlinear-reconstruction]</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="an">tags:</span><span class="co"> [autoencoder, pca, reconstruction, memorization, extrapolation, negative-control]</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="an">prerequisites:</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/methods/autoencoder-baseline.qmd</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/methods/principal-component-analysis.qmd</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="an">related:</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/linear-subspace.qmd</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/manifold.qmd</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/intrinsic-dimension.qmd</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co">- toy-models/static-linear-latent-recovery.qmd</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="an">created:</span><span class="co"> 2026-08-19</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="an">updated:</span><span class="co"> 2026-08-20</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="fu"># Bounded Nonlinear Reconstruction</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>This L1/stable Candidate G Toy Model asks whether one fixed small nonlinear autoencoder improves held-out reconstruction over rank-matched linear methods on a known curved simulator, while controls expose full-dimensional data, nuisance variance, finite-sample capacity, and extrapolation. Numerical values are deterministic outputs under master seed <span class="in">`20260819`</span>; they are conditional on the declared architecture, optimizer, preprocessing, splits, and loss.</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>**Assumed background:** centered/scaled PCA, deterministic feed-forward networks, reverse-mode differentiation, full-batch Adam, and leakage-safe train/validation/test evaluation.</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>For observations generated from one scalar through a fixed curved map into six features:</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>does a one-coordinate nonlinear bottleneck improve held-out MSE over the training mean, rank-one PCA, and a trained linear autoencoder in the identical standardized metric;</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>does learning the encoder improve on a frozen random nonlinear encoder with a trained decoder;</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>are reconstruction, code activity, and checkpoint choice stable across five predeclared seeds;</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>how do results change for full-dimensional Gaussian data, independent high-variance nuisance features, few samples with a larger architecture, and shifted test support; and</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>which conclusions remain strictly about reconstruction rather than manifold structure, intrinsic dimension, unique coordinates, representation, or mechanism?</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ground truth</span></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>The ambient dimension is $p=6$ and the scoring-only parameter is $s$. For curved conditions,</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>g(s)=</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>\begin{pmatrix}</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>s<span class="sc">\\</span> s^2<span class="sc">\\</span>0.35\sin(2s)<span class="sc">\\</span>0.2s^3<span class="sc">\\</span>\cos(s)-\sin(1.5)/1.5<span class="sc">\\</span>0.4\sin(3s)</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>\end{pmatrix},</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>and</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>x=g(s)+\epsilon,\qquad \epsilon\sim\mathcal N(0,0.06^2I_6).</span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>Nominal train, validation, and test values use $s\sim\operatorname{Uniform}<span class="co">[</span><span class="ot">-1.5,1.5</span><span class="co">]</span>$. The shifted-range test draws both signs with $|s|\sim\operatorname{Uniform}<span class="co">[</span><span class="ot">1.5,2.4</span><span class="co">]</span>$, while its train and validation samples remain in range. The implementation retains $s$ and $g(s)$ for simulation scoring only; neither is a training target.</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>The full-dimensional control draws from a full-rank Gaussian whose population mean and covariance exactly match the nominal curved **observable** distribution, including $0.06^2I_6$ noise. A fixed 256-node Gauss--Legendre rule on $<span class="co">[</span><span class="ot">-1.5,1.5</span><span class="co">]</span>$ computes those moments. The resulting covariance eigenvalues are approximately</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a>(0.85225,0.53472,0.10844,0.00563,0.00378,0.00360),</span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>so the Gaussian remains full rank while having no scalar generator truth. Executable target-moment discrepancies are zero; finite sampled splits are permitted ordinary sampling deviations. A one-dimensional bottleneck applied to this condition is imposed compression, not a dimension estimate.</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a><span class="fu">## Generative model</span></span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a>Independent split sizes are:</span>
<span id="cb4-66"><a href="#cb4-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-67"><a href="#cb4-67" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Condition <span class="pp">|</span> Train <span class="pp">|</span> Validation <span class="pp">|</span> Test <span class="pp">|</span></span>
<span id="cb4-68"><a href="#cb4-68" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb4-69"><a href="#cb4-69" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> nominal curved <span class="pp">|</span> 320 <span class="pp">|</span> 160 <span class="pp">|</span> 240 <span class="pp">|</span></span>
<span id="cb4-70"><a href="#cb4-70" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> full-dimensional Gaussian <span class="pp">|</span> 320 <span class="pp">|</span> 160 <span class="pp">|</span> 240 <span class="pp">|</span></span>
<span id="cb4-71"><a href="#cb4-71" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> high-variance nuisance <span class="pp">|</span> 320 <span class="pp">|</span> 160 <span class="pp">|</span> 240 <span class="pp">|</span></span>
<span id="cb4-72"><a href="#cb4-72" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> few-sample/high-capacity <span class="pp">|</span> 40 <span class="pp">|</span> 80 <span class="pp">|</span> 240 <span class="pp">|</span></span>
<span id="cb4-73"><a href="#cb4-73" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> shifted range <span class="pp">|</span> 320 <span class="pp">|</span> 160 <span class="pp">|</span> 240 <span class="pp">|</span></span>
<span id="cb4-74"><a href="#cb4-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-75"><a href="#cb4-75" aria-hidden="true" tabindex="-1"></a>For the nuisance condition, independent Gaussian noise with standard deviation 2.5 is added to features 5--6 after the curved signal and ordinary noise. This separates standardized objective performance from original-unit error dominated by scientifically uninformative variance.</span>
<span id="cb4-76"><a href="#cb4-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-77"><a href="#cb4-77" aria-hidden="true" tabindex="-1"></a>All streams use <span class="in">`Generator(PCG64(SeedSequence(words)))`</span>. Generation, training-only standardization, initialization, optimization, validation checkpointing, seed selection, scoring, plotting, and verification are separate functions.</span>
<span id="cb4-78"><a href="#cb4-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-79"><a href="#cb4-79" aria-hidden="true" tabindex="-1"></a><span class="fu">## Parameters</span></span>
<span id="cb4-80"><a href="#cb4-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-81"><a href="#cb4-81" aria-hidden="true" tabindex="-1"></a>Every condition uses a training-fitted feature mean and population-divisor standard deviation. All deterministic methods optimize or are scored in the same transformed-coordinate Euclidean MSE, and reconstructions are also returned to original units.</span>
<span id="cb4-82"><a href="#cb4-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-83"><a href="#cb4-83" aria-hidden="true" tabindex="-1"></a>The bottleneck width is one. There are no skip connections, stochastic layers, denoising, sparsity, or output nonlinearities.</span>
<span id="cb4-84"><a href="#cb4-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-85"><a href="#cb4-85" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Family <span class="pp">|</span> Architecture <span class="pp">|</span> Trainable parameters <span class="pp">|</span></span>
<span id="cb4-86"><a href="#cb4-86" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---:|</span></span>
<span id="cb4-87"><a href="#cb4-87" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Trained linear AE <span class="pp">|</span> $6\to1\to6$ <span class="pp">|</span> 19 <span class="pp">|</span></span>
<span id="cb4-88"><a href="#cb4-88" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Small nonlinear AE <span class="pp">|</span> $6\to8\to1\to8\to6$ <span class="pp">|</span> 135 <span class="pp">|</span></span>
<span id="cb4-89"><a href="#cb4-89" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Frozen random encoder, ordinary conditions <span class="pp">|</span> frozen $6\to8\to1$, trained $1\to8\to6$ <span class="pp">|</span> 70 trained, 65 frozen, 135 total <span class="pp">|</span></span>
<span id="cb4-90"><a href="#cb4-90" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Few-sample nonlinear AE <span class="pp">|</span> $6\to32\to1\to32\to6$ <span class="pp">|</span> 519 trainable <span class="pp">|</span></span>
<span id="cb4-91"><a href="#cb4-91" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Few-sample frozen encoder <span class="pp">|</span> frozen $6\to32\to1$, trained $1\to32\to6$ <span class="pp">|</span> 262 trained, 257 frozen, 519 total <span class="pp">|</span></span>
<span id="cb4-92"><a href="#cb4-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-93"><a href="#cb4-93" aria-hidden="true" tabindex="-1"></a>Five predeclared seeds are <span class="in">`0,1,2,3,4`</span>. Initialization is family-specific and recorded in the manifest:</span>
<span id="cb4-94"><a href="#cb4-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-95"><a href="#cb4-95" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>the linear AE is a **PCA-warm-started optimization control**: encoder/decoder weights begin at the training rank-one PCA direction plus seed-specific $\mathcal N(0,0.02^2)$ perturbations, with zero biases;</span>
<span id="cb4-96"><a href="#cb4-96" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>nonlinear AE weights use independent centered Normal draws with Glorot-like scale $\sqrt{2/(fan_{in}+fan_{out})}$ and zero biases; and</span>
<span id="cb4-97"><a href="#cb4-97" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>the frozen encoder uses fixed centered Normal weights with variances $1/6$ and $1/H$ and small random encoder biases, while its trainable decoder uses Glorot-like centered Normal weights and zero decoder biases.</span>
<span id="cb4-98"><a href="#cb4-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-99"><a href="#cb4-99" aria-hidden="true" tabindex="-1"></a>Training uses manual full-batch Adam with $(\beta_1,\beta_2,\epsilon)=(0.9,0.999,10^{-8})$, no weight decay, and linear output. Learning rates are 0.025 for linear AE, 0.012 for nonlinear AE, and 0.015 for the frozen-encoder decoder. Each family has at most 900 epochs and patience 120. Validation selects the earliest strict minimum per seed, then the seed with minimum validation loss and lower-seed tie breaking. Test data never select an epoch or seed.</span>
<span id="cb4-100"><a href="#cb4-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-101"><a href="#cb4-101" aria-hidden="true" tabindex="-1"></a>These are LDG design choices, not literature-supplied optimal settings.</span>
<span id="cb4-102"><a href="#cb4-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-103"><a href="#cb4-103" aria-hidden="true" tabindex="-1"></a><span class="fu">## Simulation</span></span>
<span id="cb4-104"><a href="#cb4-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-105"><a href="#cb4-105" aria-hidden="true" tabindex="-1"></a><span class="fu">### Nominal curved condition</span></span>
<span id="cb4-106"><a href="#cb4-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-107"><a href="#cb4-107" aria-hidden="true" tabindex="-1"></a>This is the primary nonlinear-reconstruction condition. Generator-code correlations are permitted only as simulation diagnostics after fitting.</span>
<span id="cb4-108"><a href="#cb4-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-109"><a href="#cb4-109" aria-hidden="true" tabindex="-1"></a><span class="fu">### Full-dimensional Gaussian</span></span>
<span id="cb4-110"><a href="#cb4-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-111"><a href="#cb4-111" aria-hidden="true" tabindex="-1"></a>The moment-matched full-rank Gaussian has no $s$ or noiseless one-dimensional map. Code--$s$, monotonicity, and generator-recovery rows are omitted. Any nonlinear reconstruction advantage remains a compression result after controlling first and second population moments.</span>
<span id="cb4-112"><a href="#cb4-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-113"><a href="#cb4-113" aria-hidden="true" tabindex="-1"></a><span class="fu">### High-variance nuisance</span></span>
<span id="cb4-114"><a href="#cb4-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-115"><a href="#cb4-115" aria-hidden="true" tabindex="-1"></a>The first four features retain curved signal; the final two receive large independent nuisance variance. Report structural-feature and nuisance-feature MSE separately. Neither standardized nor original-unit MSE is declared universally correct.</span>
<span id="cb4-116"><a href="#cb4-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-117"><a href="#cb4-117" aria-hidden="true" tabindex="-1"></a><span class="fu">### Few-sample/high-capacity</span></span>
<span id="cb4-118"><a href="#cb4-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-119"><a href="#cb4-119" aria-hidden="true" tabindex="-1"></a>Only 40 rows train both the 519-parameter nonlinear model and the architecture-matched width-32 frozen-encoder control with 257 frozen and 262 trained decoder parameters. Report complete train, validation, and test errors and seed variation. In this realized dataset validation selection prevents a dramatic memorization gap; this negative control remains informative even though the expected failure is not forced.</span>
<span id="cb4-120"><a href="#cb4-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-121"><a href="#cb4-121" aria-hidden="true" tabindex="-1"></a><span class="fu">### Shifted range</span></span>
<span id="cb4-122"><a href="#cb4-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-123"><a href="#cb4-123" aria-hidden="true" tabindex="-1"></a>The model and standardizer are fitted only in range and applied unchanged outside training support. This is extrapolation, not another validation split.</span>
<span id="cb4-124"><a href="#cb4-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-125"><a href="#cb4-125" aria-hidden="true" tabindex="-1"></a><span class="fu">## Visualization</span></span>
<span id="cb4-126"><a href="#cb4-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-127"><a href="#cb4-127" aria-hidden="true" tabindex="-1"></a>The single composite <span class="in">`summary.png`</span> shows bounded nominal reconstructions, selected test reconstruction metrics across conditions, selected loss histories, and code-versus-$s$ diagnostics for nominal and shifted tests.</span>
<span id="cb4-128"><a href="#cb4-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-129"><a href="#cb4-129" aria-hidden="true" tabindex="-1"></a><span class="al">![Bounded nonlinear reconstruction diagnostic](artifacts/bounded-nonlinear-reconstruction/summary.png)</span></span>
<span id="cb4-130"><a href="#cb4-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-131"><a href="#cb4-131" aria-hidden="true" tabindex="-1"></a>The figure is diagnostic only. All methods use training-only standardization; validation selects checkpoints/seeds; test data do not select models. Code plots are simulation-side diagnostics, not manifold or intrinsic-coordinate evidence.</span>
<span id="cb4-132"><a href="#cb4-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-133"><a href="#cb4-133" aria-hidden="true" tabindex="-1"></a><span class="fu">## Expected behavior</span></span>
<span id="cb4-134"><a href="#cb4-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-135"><a href="#cb4-135" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rank-one PCA is the analytic linear reconstruction reference. A well-trained linear AE should approach its reconstructed subspace and loss <span class="co">[</span><span class="ot">@BourlardKamp1988; @BaldiHornik1989</span><span class="co">]</span>.</span>
<span id="cb4-136"><a href="#cb4-136" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A small nonlinear AE can improve interpolation on the curved generator without proving that an arbitrary dataset is one-dimensional or manifold-valued.</span>
<span id="cb4-137"><a href="#cb4-137" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Frozen random nonlinear features can reconstruct some structure, so their full seed distribution is necessary before crediting learned encoding.</span>
<span id="cb4-138"><a href="#cb4-138" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Full-dimensional Gaussian data provide no valid scalar-generator recovery claim even if a flexible model improves MSE.</span>
<span id="cb4-139"><a href="#cb4-139" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Standardization can prevent nuisance features from dominating the optimized metric while original-unit error remains nuisance-dominated.</span>
<span id="cb4-140"><a href="#cb4-140" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Out-of-range reconstruction and code ordering may degrade sharply despite good in-range validation.</span>
<span id="cb4-141"><a href="#cb4-141" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A larger network with few samples can overfit, but predeclared validation stopping may also prevent the intended dramatic failure. Negative controls are reported, not tuned to guarantee a story.</span>
<span id="cb4-142"><a href="#cb4-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-143"><a href="#cb4-143" aria-hidden="true" tabindex="-1"></a><span class="fu">## Parameter manipulations</span></span>
<span id="cb4-144"><a href="#cb4-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-145"><a href="#cb4-145" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Condition <span class="pp">|</span> Changed assumption <span class="pp">|</span> Diagnostic <span class="pp">|</span></span>
<span id="cb4-146"><a href="#cb4-146" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb4-147"><a href="#cb4-147" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`nominal_curved`</span> <span class="pp">|</span> none <span class="pp">|</span> bounded nonlinear held-out gain <span class="pp">|</span></span>
<span id="cb4-148"><a href="#cb4-148" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`full_dimensional_gaussian`</span> <span class="pp">|</span> no scalar curved generator <span class="pp">|</span> imposed one-code compression <span class="pp">|</span></span>
<span id="cb4-149"><a href="#cb4-149" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`high_variance_nuisance`</span> <span class="pp">|</span> large independent variance in features 5--6 <span class="pp">|</span> structural/nuisance and metric dependence <span class="pp">|</span></span>
<span id="cb4-150"><a href="#cb4-150" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`few_sample_high_capacity`</span> <span class="pp">|</span> 40 training rows and width 32 <span class="pp">|</span> capacity, seed, and generalization gap <span class="pp">|</span></span>
<span id="cb4-151"><a href="#cb4-151" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`shifted_range`</span> <span class="pp">|</span> test support outside training range <span class="pp">|</span> extrapolation and code ordering <span class="pp">|</span></span>
<span id="cb4-152"><a href="#cb4-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-153"><a href="#cb4-153" aria-hidden="true" tabindex="-1"></a>No condition, architecture, seed set, optimizer budget, or noise magnitude is retuned from test results.</span>
<span id="cb4-154"><a href="#cb4-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-155"><a href="#cb4-155" aria-hidden="true" tabindex="-1"></a><span class="fu">## Sanity checks</span></span>
<span id="cb4-156"><a href="#cb4-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-157"><a href="#cb4-157" aria-hidden="true" tabindex="-1"></a>The verifier checks:</span>
<span id="cb4-158"><a href="#cb4-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-159"><a href="#cb4-159" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>exact split regeneration for observations, $s$, and noiseless curves;</span>
<span id="cb4-160"><a href="#cb4-160" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>test-observation poisoning leaves standardization, all candidates, checkpoint histories, and selected seeds unchanged;</span>
<span id="cb4-161"><a href="#cb4-161" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>poisoning every $s$ and noiseless-truth array leaves all observation-only fits and reconstructions unchanged;</span>
<span id="cb4-162"><a href="#cb4-162" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>PCA and the analytic linear reconstruction are identical;</span>
<span id="cb4-163"><a href="#cb4-163" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>selected trained-linear-AE composite projector, subspace angle, and training MSE approach PCA within declared tolerances; failure would be labelled optimization failure;</span>
<span id="cb4-164"><a href="#cb4-164" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>centered finite-difference gradients for linear, nonlinear, and frozen-decoder networks agree with analytic backpropagation;</span>
<span id="cb4-165"><a href="#cb4-165" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>validation checkpoint losses and earliest-minimum epochs recompute exactly;</span>
<span id="cb4-166"><a href="#cb4-166" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>validation seed selection replays exactly;</span>
<span id="cb4-167"><a href="#cb4-167" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>repeated full-batch Adam training is deterministic;</span>
<span id="cb4-168"><a href="#cb4-168" aria-hidden="true" tabindex="-1"></a><span class="ss">10. </span>frozen encoder parameters never change;</span>
<span id="cb4-169"><a href="#cb4-169" aria-hidden="true" tabindex="-1"></a><span class="ss">11. </span>bottleneck shape is exactly $n\times1$, parameter counts match architecture, and no skip path exists;</span>
<span id="cb4-170"><a href="#cb4-170" aria-hidden="true" tabindex="-1"></a><span class="ss">12. </span>all losses, parameters, codes, reconstructions, and metric values are finite;</span>
<span id="cb4-171"><a href="#cb4-171" aria-hidden="true" tabindex="-1"></a><span class="ss">13. </span>metric rows have the exact schema, nonempty labels, finite values, and unique composite keys; and</span>
<span id="cb4-172"><a href="#cb4-172" aria-hidden="true" tabindex="-1"></a><span class="ss">14. </span>a clean temporary regeneration produces byte-identical generated artifacts.</span>
<span id="cb4-173"><a href="#cb4-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-174"><a href="#cb4-174" aria-hidden="true" tabindex="-1"></a>These checks support implementation integrity, not manifold or mechanism claims.</span>
<span id="cb4-175"><a href="#cb4-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-176"><a href="#cb4-176" aria-hidden="true" tabindex="-1"></a><span class="fu">## Failure cases</span></span>
<span id="cb4-177"><a href="#cb4-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-178"><a href="#cb4-178" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Different metrics for PCA and AE:** preprocessing or test-fitted scaling makes comparison invalid.</span>
<span id="cb4-179"><a href="#cb4-179" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Poor linear optimization called nonlinear gain:** analytic PCA remains the authoritative linear baseline.</span>
<span id="cb4-180"><a href="#cb4-180" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Best test seed selection:** all checkpoint and seed choices must use validation only.</span>
<span id="cb4-181"><a href="#cb4-181" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Low training error called recovery:** the full train/validation/test gap must remain visible.</span>
<span id="cb4-182"><a href="#cb4-182" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Frozen encoder silently updated:** encoder immutability is executable-checked.</span>
<span id="cb4-183"><a href="#cb4-183" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Dead or collapsed code hidden:** code variance, range, and collision diagnostics are reported.</span>
<span id="cb4-184"><a href="#cb4-184" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Nuisance reconstruction called scientific signal:** structural and nuisance errors remain separate.</span>
<span id="cb4-185"><a href="#cb4-185" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Full Gaussian called one-dimensional:** no scalar truth rows exist for that condition.</span>
<span id="cb4-186"><a href="#cb4-186" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**In-range interpolation generalized to shifted support:** shifted metrics are explicitly extrapolation.</span>
<span id="cb4-187"><a href="#cb4-187" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Code correlation called coordinate identification:** correlation with $s$ is scoring-only and does not identify a unique code.</span>
<span id="cb4-188"><a href="#cb4-188" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**One active bottleneck called intrinsic dimension:** bottleneck width is fixed by the analyst.</span>
<span id="cb4-189"><a href="#cb4-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-190"><a href="#cb4-190" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recovery task</span></span>
<span id="cb4-191"><a href="#cb4-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-192"><a href="#cb4-192" aria-hidden="true" tabindex="-1"></a><span class="fu">### Mean and PCA</span></span>
<span id="cb4-193"><a href="#cb4-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-194"><a href="#cb4-194" aria-hidden="true" tabindex="-1"></a>The transformed training mean is zero. Rank-one PCA fits the leading right singular vector and applies its orthogonal projector.</span>
<span id="cb4-195"><a href="#cb4-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-196"><a href="#cb4-196" aria-hidden="true" tabindex="-1"></a><span class="fu">### Linear autoencoder</span></span>
<span id="cb4-197"><a href="#cb4-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-198"><a href="#cb4-198" aria-hidden="true" tabindex="-1"></a>The trainable linear encoder and decoder are optimized under the same MSE. The composite map, not individual factors, is compared with the PCA projector.</span>
<span id="cb4-199"><a href="#cb4-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-200"><a href="#cb4-200" aria-hidden="true" tabindex="-1"></a><span class="fu">### Nonlinear autoencoder</span></span>
<span id="cb4-201"><a href="#cb4-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-202"><a href="#cb4-202" aria-hidden="true" tabindex="-1"></a>For hidden width $h$, the encoder is $\tanh(W_eu+b_e)$ followed by one linear code; the decoder applies one tanh hidden layer and a linear output. All trainable parameters use the fixed optimizer protocol.</span>
<span id="cb4-203"><a href="#cb4-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-204"><a href="#cb4-204" aria-hidden="true" tabindex="-1"></a><span class="fu">### Frozen random encoder</span></span>
<span id="cb4-205"><a href="#cb4-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-206"><a href="#cb4-206" aria-hidden="true" tabindex="-1"></a>The nonlinear encoder is initialized and copied before training. Only the decoder is optimized. This controls whether generic frozen nonlinear features are sufficient.</span>
<span id="cb4-207"><a href="#cb4-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-208"><a href="#cb4-208" aria-hidden="true" tabindex="-1"></a><span class="fu">## Candidate analysis methods</span></span>
<span id="cb4-209"><a href="#cb4-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-210"><a href="#cb4-210" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>training mean;</span>
<span id="cb4-211"><a href="#cb4-211" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>rank-one PCA;</span>
<span id="cb4-212"><a href="#cb4-212" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>trained rank-one linear AE;</span>
<span id="cb4-213"><a href="#cb4-213" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>fixed small nonlinear tanh AE;</span>
<span id="cb4-214"><a href="#cb4-214" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>frozen random tanh encoder with trained decoder; and</span>
<span id="cb4-215"><a href="#cb4-215" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>the larger nonlinear architecture in the few-sample stress.</span>
<span id="cb4-216"><a href="#cb4-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-217"><a href="#cb4-217" aria-hidden="true" tabindex="-1"></a>No method receives $s$, noiseless $g(s)$, test preprocessing statistics, or test-selected epochs.</span>
<span id="cb4-218"><a href="#cb4-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-219"><a href="#cb4-219" aria-hidden="true" tabindex="-1"></a><span class="fu">## Evaluation</span></span>
<span id="cb4-220"><a href="#cb4-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-221"><a href="#cb4-221" aria-hidden="true" tabindex="-1"></a><span class="in">`metrics.csv`</span> contains:</span>
<span id="cb4-222"><a href="#cb4-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-223"><a href="#cb4-223" aria-hidden="true" tabindex="-1"></a><span class="in">```text</span></span>
<span id="cb4-224"><a href="#cb4-224" aria-hidden="true" tabindex="-1"></a><span class="in">split,condition,preprocessing,method,seed,selection,target,metric,value</span></span>
<span id="cb4-225"><a href="#cb4-225" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb4-226"><a href="#cb4-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-227"><a href="#cb4-227" aria-hidden="true" tabindex="-1"></a>It reports transformed and original-unit MSE by split, per-feature MSE, train--test gaps, parameter counts, selected seeds/epochs, all seed validation records, code mean/variance/range and collapse/dead indicators, and condition-specific structural/nuisance or generator diagnostics.</span>
<span id="cb4-228"><a href="#cb4-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-229"><a href="#cb4-229" aria-hidden="true" tabindex="-1"></a><span class="fu">### Empirical results</span></span>
<span id="cb4-230"><a href="#cb4-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-231"><a href="#cb4-231" aria-hidden="true" tabindex="-1"></a>Selected-model test original-unit MSE:</span>
<span id="cb4-232"><a href="#cb4-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-233"><a href="#cb4-233" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Condition <span class="pp">|</span> PCA <span class="pp">|</span> Linear AE <span class="pp">|</span> Nonlinear AE <span class="pp">|</span> Frozen encoder <span class="pp">|</span></span>
<span id="cb4-234"><a href="#cb4-234" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---:|</span></span>
<span id="cb4-235"><a href="#cb4-235" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Nominal curved <span class="pp">|</span> 0.1082 <span class="pp">|</span> 0.1085 <span class="pp">|</span> **0.00958** <span class="pp">|</span> 0.1288 <span class="pp">|</span></span>
<span id="cb4-236"><a href="#cb4-236" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Moment-matched full-dimensional Gaussian <span class="pp">|</span> 0.11245 <span class="pp">|</span> 0.11213 <span class="pp">|</span> 0.11318 <span class="pp">|</span> 0.15416 <span class="pp">|</span></span>
<span id="cb4-237"><a href="#cb4-237" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> High-variance nuisance <span class="pp">|</span> 2.0780 <span class="pp">|</span> 2.0854 <span class="pp">|</span> 1.8351 <span class="pp">|</span> **1.7160** <span class="pp">|</span></span>
<span id="cb4-238"><a href="#cb4-238" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Few-sample/high-capacity <span class="pp">|</span> 0.1177 <span class="pp">|</span> 0.1175 <span class="pp">|</span> **0.00525** <span class="pp">|</span> 0.0389 <span class="pp">|</span></span>
<span id="cb4-239"><a href="#cb4-239" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Shifted range <span class="pp">|</span> 2.1218 <span class="pp">|</span> 2.1228 <span class="pp">|</span> **0.9146** <span class="pp">|</span> 2.7996 <span class="pp">|</span></span>
<span id="cb4-240"><a href="#cb4-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-241"><a href="#cb4-241" aria-hidden="true" tabindex="-1"></a>The nominal nonlinear code has absolute Pearson/Spearman correlation 0.901/0.846 with scoring-only $s$. The reported collision diagnostic is a nonstandard LDG threshold check: among all $n(n-1)/2=28{,}680$ test pairs, define a close-code denominator by $|\Delta z|\le0.05$ of the observed code range; a collision additionally requires $|\Delta s|&gt;0.5$. The selected nominal model has 4,135 close-code pairs and 39 collisions, fraction 0.00943. These thresholds and values do not establish injectivity or unique coordinates. Under nuisance variance, nonlinear structural-feature MSE is 0.0125 while nuisance-feature MSE is 5.48, showing why aggregate original-unit loss can obscure scientific structure. The few-sample nonlinear train/test MSE is 0.00321/0.00525: the larger network fits well but the predeclared validation protocol avoids a dramatic memorization failure. Shifted nonlinear test MSE is computed with the exact nominal train/validation bundles, standardizer, candidate histories, checkpoints, selected seeds, and fitted models; only the exterior-support test bundle differs. Its selected code has 13,390 close-code pairs and 1,852 collisions, fraction 0.1383, exposing extrapolation limits.</span>
<span id="cb4-242"><a href="#cb4-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-243"><a href="#cb4-243" aria-hidden="true" tabindex="-1"></a>The moment-matched Gaussian nonlinear result is slightly worse than PCA/linear AE in this realization and is not evidence for one-dimensional structure. Seed variability remains in the full metric table and selection is validation-only.</span>
<span id="cb4-244"><a href="#cb4-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-245"><a href="#cb4-245" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpretation</span></span>
<span id="cb4-246"><a href="#cb4-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-247"><a href="#cb4-247" aria-hidden="true" tabindex="-1"></a>The nominal result establishes only that this selected finite nonlinear network reconstructs held-out samples from this curved simulator better than rank-one PCA under the declared standardized MSE. The full-dimensional, nuisance, few-sample, frozen-feature, and shifted controls show that reconstruction gains can coexist with absent one-dimensional truth, irrelevant variance, capacity sensitivity, useful random features, or poor extrapolation.</span>
<span id="cb4-248"><a href="#cb4-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-249"><a href="#cb4-249" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning title="What this does NOT imply"}</span>
<span id="cb4-250"><a href="#cb4-250" aria-hidden="true" tabindex="-1"></a>Low reconstruction error, an active one-dimensional code, or correlation with a known simulator parameter does not prove a manifold, intrinsic dimension, unique latent coordinate, representation, causal variable, dynamics, or mechanism.</span>
<span id="cb4-251"><a href="#cb4-251" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb4-252"><a href="#cb4-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-253"><a href="#cb4-253" aria-hidden="true" tabindex="-1"></a><span class="fu">## What this toy model does NOT establish</span></span>
<span id="cb4-254"><a href="#cb4-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-255"><a href="#cb4-255" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a model-free intrinsic dimension;</span>
<span id="cb4-256"><a href="#cb4-256" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a smooth or injective manifold chart;</span>
<span id="cb4-257"><a href="#cb4-257" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>unique encoder/decoder parameters or code axes;</span>
<span id="cb4-258"><a href="#cb4-258" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a probability model, posterior, or uncertainty distribution;</span>
<span id="cb4-259"><a href="#cb4-259" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>dynamics, temporal order, a vector field, or state transition;</span>
<span id="cb4-260"><a href="#cb4-260" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a causal, biological, or physical mechanism;</span>
<span id="cb4-261"><a href="#cb4-261" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>universal nonlinear superiority over PCA; or</span>
<span id="cb4-262"><a href="#cb4-262" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>reliable extrapolation outside the tested range.</span>
<span id="cb4-263"><a href="#cb4-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-264"><a href="#cb4-264" aria-hidden="true" tabindex="-1"></a><span class="fu">## Extensions to real data</span></span>
<span id="cb4-265"><a href="#cb4-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-266"><a href="#cb4-266" aria-hidden="true" tabindex="-1"></a>Real-data use must define independent units, feature scaling, missingness, architecture/capacity search, nested validation, subject/session shift, nuisance features, and the scientific cost of per-feature errors. A reconstruction baseline should be accompanied by PCA, random-feature, capacity, seed, leakage, and distribution-shift checks. Codes should not receive semantic or mechanistic names from geometry alone.</span>
<span id="cb4-267"><a href="#cb4-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-268"><a href="#cb4-268" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reproducibility</span></span>
<span id="cb4-269"><a href="#cb4-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-270"><a href="#cb4-270" aria-hidden="true" tabindex="-1"></a>The bounded artifact set is:</span>
<span id="cb4-271"><a href="#cb4-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-272"><a href="#cb4-272" aria-hidden="true" tabindex="-1"></a><span class="in">```text</span></span>
<span id="cb4-273"><a href="#cb4-273" aria-hidden="true" tabindex="-1"></a><span class="in">toy-models/bounded-nonlinear-reconstruction.py</span></span>
<span id="cb4-274"><a href="#cb4-274" aria-hidden="true" tabindex="-1"></a><span class="in">toy-models/artifacts/bounded-nonlinear-reconstruction/manifest.json</span></span>
<span id="cb4-275"><a href="#cb4-275" aria-hidden="true" tabindex="-1"></a><span class="in">toy-models/artifacts/bounded-nonlinear-reconstruction/metrics.csv</span></span>
<span id="cb4-276"><a href="#cb4-276" aria-hidden="true" tabindex="-1"></a><span class="in">toy-models/artifacts/bounded-nonlinear-reconstruction/diagnostics.json</span></span>
<span id="cb4-277"><a href="#cb4-277" aria-hidden="true" tabindex="-1"></a><span class="in">toy-models/artifacts/bounded-nonlinear-reconstruction/summary.png</span></span>
<span id="cb4-278"><a href="#cb4-278" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb4-279"><a href="#cb4-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-280"><a href="#cb4-280" aria-hidden="true" tabindex="-1"></a>The bundled-runtime command is:</span>
<span id="cb4-281"><a href="#cb4-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-282"><a href="#cb4-282" aria-hidden="true" tabindex="-1"></a><span class="in">```bash</span></span>
<span id="cb4-283"><a href="#cb4-283" aria-hidden="true" tabindex="-1"></a><span class="ex">/Users/bytedance/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3</span> toy-models/bounded-nonlinear-reconstruction.py</span>
<span id="cb4-284"><a href="#cb4-284" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb4-285"><a href="#cb4-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-286"><a href="#cb4-286" aria-hidden="true" tabindex="-1"></a>Default execution generates and verifies, including temporary byte-identical regeneration. The manifest records generator and split contracts, preprocessing, architectures, parameter counts, seeds, optimizer/checkpoint rules, applicability, runtime, commands, and hashes.</span>
<span id="cb4-287"><a href="#cb4-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-288"><a href="#cb4-288" aria-hidden="true" tabindex="-1"></a><span class="fu">### Evidence inspected</span></span>
<span id="cb4-289"><a href="#cb4-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-290"><a href="#cb4-290" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Bourlard and Kamp (1988):** the complete four-page article was inspected for the SVD solution, centering/bias treatment, linear hidden-unit relationship, small-signal sigmoid discussion, experiment, and conclusion <span class="co">[</span><span class="ot">@BourlardKamp1988</span><span class="co">]</span>.</span>
<span id="cb4-291"><a href="#cb4-291" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Baldi and Hornik (1989):** the complete six-page article was inspected for the squared-error landscape, principal-subspace optimum, factor nonuniqueness, boundary cases, algorithm discussion, and appendices <span class="co">[</span><span class="ot">@BaldiHornik1989</span><span class="co">]</span>.</span>
<span id="cb4-292"><a href="#cb4-292" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Kramer (1991):** the nonlinear auto-associative architecture, reconstruction objective, capacity/overfitting discussion, training procedure, examples, and conclusion were inspected; sequential-factor and related-work details were read only at overview depth <span class="co">[</span><span class="ot">@Kramer1991</span><span class="co">]</span>.</span>
<span id="cb4-293"><a href="#cb4-293" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Goodfellow, Bengio, and Courville (2016), Chapter 14:** the introduction, undercomplete autoencoders, capacity and copying failures, relevant real-valued/MSE material, manifold-learning interpretation limits, and optimization/generalization discussion were inspected. Excluded autoencoder variants were not inspected equation by equation <span class="co">[</span><span class="ot">@GoodfellowBengioCourville2016, chap. 14</span><span class="co">]</span>.</span>
<span id="cb4-294"><a href="#cb4-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-295"><a href="#cb4-295" aria-hidden="true" tabindex="-1"></a>These sources do not supply this simulator, architecture, seeds, optimizer budgets, thresholds, or artifact format; those are LDG design choices.</span>
<span id="cb4-296"><a href="#cb4-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-297"><a href="#cb4-297" aria-hidden="true" tabindex="-1"></a><span class="fu">## Maturity checklist</span></span>
<span id="cb4-298"><a href="#cb4-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-299"><a href="#cb4-299" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Complete L1/stable Toy Model schema and artifact contract.</span>
<span id="cb4-300"><a href="#cb4-300" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Known curved generator, full-dimensional, nuisance, few-sample, and shift controls are explicit.</span>
<span id="cb4-301"><a href="#cb4-301" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Mean, PCA, linear AE, nonlinear AE, and frozen-encoder comparisons share training-only preprocessing and MSE geometry.</span>
<span id="cb4-302"><a href="#cb4-302" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Architecture, parameter counts, optimizer, budgets, patience, seeds, checkpoints, and selection are fixed.</span>
<span id="cb4-303"><a href="#cb4-303" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Split losses, feature errors, seed distributions, code activity, generator and extrapolation diagnostics are reported.</span>
<span id="cb4-304"><a href="#cb4-304" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Gradient, checkpoint, seed, leakage, PCA/linear, architecture, and deterministic oracles pass.</span>
<span id="cb4-305"><a href="#cb4-305" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Manifold, dimension, coordinate, dynamics, mechanism, representation, and causal overclaims are prohibited.</span>
<span id="cb4-306"><a href="#cb4-306" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Independent scientific review PASS.</span>
<span id="cb4-307"><a href="#cb4-307" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Independent implementation review PASS.</span>
<span id="cb4-308"><a href="#cb4-308" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Repository validation and renders PASS after review.</span>
<span id="cb4-309"><a href="#cb4-309" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Mechanical L1/stable promotion under the recorded review decision.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>