<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Two-Dimensional Autonomous Dynamics: Generation and Recovery – Latent Dynamics &amp; Geometry</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-445b8638c3d06994fee0907d791121c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Latent Dynamics &amp; Geometry</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../knowledge/concepts/index.html"> 
<span class="menu-text">Concepts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../knowledge/methods/index.html"> 
<span class="menu-text">Methods</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../knowledge/math/index.html"> 
<span class="menu-text">Math</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../knowledge/papers/index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../toy-models/index.html"> 
<span class="menu-text">Toy Models</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../research-questions/index.html"> 
<span class="menu-text">Research Questions</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../benchmarks/index.html"> 
<span class="menu-text">Benchmarks</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AbelZheng/latent-dynamics-geometry-public"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/AbelZheng/latent-dynamics-geometry-public/discussions"> 
<span class="menu-text">Discussions</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#two-dimensional-autonomous-dynamics-generation-and-recovery" id="toc-two-dimensional-autonomous-dynamics-generation-and-recovery" class="nav-link active" data-scroll-target="#two-dimensional-autonomous-dynamics-generation-and-recovery">Two-Dimensional Autonomous Dynamics: Generation and Recovery</a>
  <ul class="collapse">
  <li><a href="#question" id="toc-question" class="nav-link" data-scroll-target="#question">Question</a></li>
  <li><a href="#ground-truth" id="toc-ground-truth" class="nav-link" data-scroll-target="#ground-truth">Ground truth</a></li>
  <li><a href="#generative-model" id="toc-generative-model" class="nav-link" data-scroll-target="#generative-model">Generative model</a></li>
  <li><a href="#parameters" id="toc-parameters" class="nav-link" data-scroll-target="#parameters">Parameters</a></li>
  <li><a href="#simulation" id="toc-simulation" class="nav-link" data-scroll-target="#simulation">Simulation</a></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization">Visualization</a></li>
  <li><a href="#expected-behavior" id="toc-expected-behavior" class="nav-link" data-scroll-target="#expected-behavior">Expected behavior</a></li>
  <li><a href="#parameter-manipulations" id="toc-parameter-manipulations" class="nav-link" data-scroll-target="#parameter-manipulations">Parameter manipulations</a></li>
  <li><a href="#sanity-checks" id="toc-sanity-checks" class="nav-link" data-scroll-target="#sanity-checks">Sanity checks</a></li>
  <li><a href="#failure-cases" id="toc-failure-cases" class="nav-link" data-scroll-target="#failure-cases">Failure cases</a></li>
  <li><a href="#recovery-task" id="toc-recovery-task" class="nav-link" data-scroll-target="#recovery-task">Recovery task</a></li>
  <li><a href="#candidate-analysis-methods" id="toc-candidate-analysis-methods" class="nav-link" data-scroll-target="#candidate-analysis-methods">Candidate analysis methods</a></li>
  <li><a href="#evaluation" id="toc-evaluation" class="nav-link" data-scroll-target="#evaluation">Evaluation</a>
  <ul class="collapse">
  <li><a href="#observed-bounded-results" id="toc-observed-bounded-results" class="nav-link" data-scroll-target="#observed-bounded-results">Observed bounded results</a></li>
  </ul></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#what-this-toy-model-does-not-establish" id="toc-what-this-toy-model-does-not-establish" class="nav-link" data-scroll-target="#what-this-toy-model-does-not-establish">What this toy model does NOT establish</a></li>
  <li><a href="#extensions-to-real-data" id="toc-extensions-to-real-data" class="nav-link" data-scroll-target="#extensions-to-real-data">Extensions to real data</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a>
  <ul class="collapse">
  <li><a href="#planning-maturity-checklist" id="toc-planning-maturity-checklist" class="nav-link" data-scroll-target="#planning-maturity-checklist">Planning maturity checklist</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Two-Dimensional Autonomous Dynamics: Generation and Recovery</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="two-dimensional-autonomous-dynamics-generation-and-recovery" class="level1">
<h1>Two-Dimensional Autonomous Dynamics: Generation and Recovery</h1>
<p>This L1 object records both the reviewed implementation contract and its bounded executable realization. Its <code>stable</code> status records owner-authorized acceptance after independent technical and implementation/result review. The generated results test the declared simulator and recovery pipeline; stable status does not validate a real system or turn recovery performance into mechanistic evidence.</p>
<p><strong>Assumed background:</strong> elementary multivariable calculus and polar coordinates; basic probability and linear algebra; polynomial regression and ridge-regression basics; finite differences and smoothing; and elementary numerical integration. These external basics are not repository prerequisites.</p>
<section id="question" class="level2">
<h2 class="anchored" data-anchor-id="question">Question</h2>
<p>Can a transparent cubic polynomial estimator recover a known nonlinear two-dimensional autonomous vector field and its held-out trajectories from directly observed, finitely sampled, noisy state coordinates, and when does it improve over a linear baseline?</p>
<p>The demonstration is deliberately narrow. It asks whether a method recovers one declared simulator under controlled sampling and noise, not whether an autonomous model is appropriate for a real system.</p>
</section>
<section id="ground-truth" class="level2">
<h2 class="anchored" data-anchor-id="ground-truth">Ground truth</h2>
<p>Let <span class="math inline">\(z(t)=(x(t),y(t))\in\mathbb R^2\)</span> and define</p>
<p><span class="math display">\[
\dot x=(\alpha-\beta r^2)x-\omega y,
\]</span></p>
<p><span class="math display">\[
\dot y=\omega x+(\alpha-\beta r^2)y,
\]</span></p>
<p>where <span class="math inline">\(r^2=x^2+y^2\)</span>, with fixed parameters</p>
<p><span class="math display">\[
\alpha=1,
\qquad
\beta=1,
\qquad
\omega=2.
\]</span></p>
<p>In polar coordinates this field has</p>
<p><span class="math display">\[
\dot r=r(1-r^2),
\qquad
\dot\theta=2.
\]</span></p>
<p>For <span class="math inline">\(r_0&gt;0\)</span>, an analytic reference solution is</p>
<p><span class="math display">\[
r(t)=\left[1+(r_0^{-2}-1)e^{-2t}\right]^{-1/2},
\qquad
\theta(t)=\theta_0+2t.
\]</span></p>
<p>Thus the origin is a fixed point, every nonzero initial condition rotates counterclockwise, and radii below or above one approach the isolated periodic orbit <span class="math inline">\(r=1\)</span>. These properties follow from the declared equations and serve as simulator checks; they are not inferred from generated plots.</p>
<p>The state space is <span class="math inline">\(\mathbb R^2\)</span>. Primary training and evaluation are restricted to trajectories initialized with <span class="math inline">\(0.35\le r_0\le1.65\)</span>. Field error is evaluated on the declared annulus</p>
<p><span class="math display">\[
\mathcal D_{\mathrm{eval}}=\{(x,y):0.35\le\sqrt{x^2+y^2}\le1.65\},
\]</span></p>
<p>so conclusions do not extend automatically to the origin or to arbitrary radii.</p>
</section>
<section id="generative-model" class="level2">
<h2 class="anchored" data-anchor-id="generative-model">Generative model</h2>
<p>Generation and observation are separate steps.</p>
<ol type="1">
<li><p>Draw an initial state <span class="math inline">\(z_0=(r_0\cos\theta_0,r_0\sin\theta_0)\)</span> from the distributions below.</p></li>
<li><p>Solve the deterministic initial-value problem <span class="math inline">\(\dot z=f(z)\)</span> from <span class="math inline">\(t=0\)</span> to <span class="math inline">\(t=8\)</span>.</p></li>
<li><p>Evaluate the same continuous latent solution at the requested observation interval <span class="math inline">\(\Delta t\)</span>.</p></li>
<li><p>Generate direct observations</p>
<p><span class="math display">\[
y_k=z(t_k)+\varepsilon_k,
\qquad
\varepsilon_k\overset{\mathrm{iid}}\sim\mathcal N(0,\sigma^2I_2).
\]</span></p></li>
</ol>
<p>The identity observation map fixes the latent coordinate convention. Sampling interval and observation noise are manipulations of the measurement process; they do not alter <span class="math inline">\(f\)</span>, its parameters, or the latent initial-condition law.</p>
</section>
<section id="parameters" class="level2">
<h2 class="anchored" data-anchor-id="parameters">Parameters</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Fixed plan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ground-truth field</td>
<td><span class="math inline">\(f(x,y)=((1-r^2)x-2y,\;2x+(1-r^2)y)\)</span></td>
</tr>
<tr class="even">
<td>Integration interval</td>
<td><span class="math inline">\(t\in[0,8]\)</span></td>
</tr>
<tr class="odd">
<td>Primary initial radii</td>
<td>exact half-split: <span class="math inline">\(U[0.35,0.75]\)</span> and <span class="math inline">\(U[1.25,1.65]\)</span></td>
</tr>
<tr class="even">
<td>Initial angles</td>
<td><span class="math inline">\(U[0,2\pi)\)</span> independently of radius</td>
</tr>
<tr class="odd">
<td>Training / test trajectories</td>
<td>64 / 40 independent initial conditions</td>
</tr>
<tr class="even">
<td>Sampling intervals</td>
<td><span class="math inline">\(\Delta t\in\{0.025,0.05,0.10\}\)</span></td>
</tr>
<tr class="odd">
<td>Observation-noise scales</td>
<td><span class="math inline">\(\sigma\in\{0,0.02,0.05\}\)</span> in state-coordinate units</td>
</tr>
<tr class="even">
<td>Noise replicates</td>
<td>10 per nonzero-noise condition; one deterministic replicate when <span class="math inline">\(\sigma=0\)</span></td>
</tr>
<tr class="odd">
<td>Primary recovery basis</td>
<td>all monomials in <span class="math inline">\((x,y)\)</span> of total degree at most three</td>
</tr>
<tr class="even">
<td>Baseline basis</td>
<td>constant plus degree-one terms only</td>
</tr>
<tr class="odd">
<td>Ridge penalty</td>
<td><span class="math inline">\(\lambda=10^{-4}\)</span> after standardizing nonconstant feature columns on training data</td>
</tr>
<tr class="even">
<td>Smoothing windows</td>
<td>21, 11, and 5 points for <span class="math inline">\(\Delta t=0.025,0.05,0.10\)</span>, respectively; cubic Savitzky–Golay polynomial</td>
</tr>
<tr class="odd">
<td>Evaluation grid</td>
<td><span class="math inline">\(\rho_i=0.35+i(1.30/26)\)</span>, <span class="math inline">\(i=0,\ldots,26\)</span>; <span class="math inline">\(\theta_j=2\pi j/64\)</span>, <span class="math inline">\(j=0,\ldots,63\)</span></td>
</tr>
</tbody>
</table>
<p>The training split contains exactly 32 initial radii from each interval; the primary test split contains exactly 20 from each. Angles are sampled independently. This exact stratification forces both splits to include trajectories approaching the cycle from both sides. Test initial conditions use independent seeds and are held out as entire trajectories.</p>
<p>For each sampling interval,</p>
<p><span class="math display">\[
t_k=k\Delta t,
\qquad
k=0,\ldots,8/\Delta t,
\]</span></p>
<p>including both endpoints. The three conditions therefore contain 321, 161, and 81 observation times, respectively. The angular grid excludes the duplicated endpoint <span class="math inline">\(2\pi\)</span>; both radial endpoints are included.</p>
</section>
<section id="simulation" class="level2">
<h2 class="anchored" data-anchor-id="simulation">Simulation</h2>
<p>The reviewed plan specified SciPy DOP853 for numerical generation. SciPy was not available in the existing approved runtime, and no dependency was installed. The executable therefore uses the exact analytic polar solution as the primary generator and checks it independently with a NumPy fixed-step fourth-order Runge–Kutta integrator using <span class="math inline">\(h=0.005\)</span>. This is an explicit implementation realization, not a silent change to the ground-truth field, time support, sampling conditions, or evaluation contract.</p>
<p>The implementation generates latent trajectories once per initial condition and derives every sampling condition from the same continuous solution. Independent paired standard-normal draws are added only after sampling and scaled by the declared <span class="math inline">\(\sigma\)</span>. Train and test arrays remain separate; no held-out time point enters feature scaling or regression fitting. The smoothing duration and every recovery hyperparameter remain fixed rather than selected on test results.</p>
<p>The executable source is <code>two-dimensional-autonomous-dynamics.py</code>. It implements the centered local-cubic filters with NumPy pseudoinverses, the declared ridge objective with NumPy linear algebra, recovered rollouts with RK4, and a composite PNG with the already available Pillow library.</p>
</section>
<section id="visualization" class="level2">
<h2 class="anchored" data-anchor-id="visualization">Visualization</h2>
<p>The bounded composite diagnostic produces:</p>
<ol type="1">
<li>true phase portraits with inner and outer trajectories and the unit cycle;</li>
<li>true and recovered vector-field arrows on the same fixed evaluation grid, shown in separate panels rather than visually subtracting one from the other;</li>
<li>metric heat maps over <span class="math inline">\((\Delta t,\sigma)\)</span> for cubic and affine oracle-rollout error; and</li>
<li>the preregistered primary comparisons plus the explicit derivative-permutation failure count.</li>
</ol>
<p>Held-out trajectory-level errors, fitted coefficients, and all failure flags/horizons remain in <code>metrics.csv</code>, <code>coefficients.csv</code>, and <code>diagnostics.json</code> rather than being compressed into the single bounded PNG.</p>
<p>Visualizations are diagnostics only. Numerical evaluation and negative controls determine whether recovery succeeded.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="artifacts/two-dimensional-autonomous-dynamics/summary.png" class="img-fluid figure-img"></p>
<figcaption>Composite generator, vector-field, condition, and primary-comparison diagnostics</figcaption>
</figure>
</div>
</section>
<section id="expected-behavior" class="level2">
<h2 class="anchored" data-anchor-id="expected-behavior">Expected behavior</h2>
<div class="callout callout-style-default callout-tip callout-titled" title="LDG Design Expectation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>LDG Design Expectation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The following expectations are falsifiable design predictions, not generated results.</p>
</div>
</div>
<ul>
<li>In the noiseless, finest-sampling condition, cubic recovery should approximate the true polynomial field and outperform the misspecified linear baseline on field and rollout error.</li>
<li>Increasing <span class="math inline">\(\sigma\)</span> or <span class="math inline">\(\Delta t\)</span> should worsen derivative estimation and downstream field recovery, although the trend need not be strictly monotone in every finite replicate.</li>
<li>The linear baseline may approximate short local segments but should miss radius-dependent contraction and expansion across the full annulus.</li>
<li>The derivative-permutation negative control should lose state-to-velocity structure and perform substantially worse than the unshuffled cubic fit.</li>
<li>Long rollouts should amplify small field-estimation errors, so one-step error may remain low after trajectory error has become appreciable.</li>
</ul>
<p>These expectations will not be enforced by retuning the simulator or estimator after results are seen. A violation is a result to diagnose.</p>
</section>
<section id="parameter-manipulations" class="level2">
<h2 class="anchored" data-anchor-id="parameter-manipulations">Parameter manipulations</h2>
<p>The primary bounded factorial design contains nine sampling/noise conditions:</p>
<p><span class="math display">\[
\Delta t\in\{0.025,0.05,0.10\}
\quad\times\quad
\sigma\in\{0,0.02,0.05\}.
\]</span></p>
<p>Only the observation schedule and observation noise change. The latent field, integration interval, initial-condition distribution, data split sizes, smoother duration, feature basis, and ridge penalty remain fixed.</p>
<p>One labeled extrapolation stress test uses 16 additional held-out initial radii drawn from <span class="math inline">\(U[1.65,1.90]\)</span> with independent angles at <span class="math inline">\((\Delta t,\sigma)=(0.05,0.02)\)</span>. It is reported separately and is not part of the primary success criterion because it begins outside the field-evaluation annulus.</p>
</section>
<section id="sanity-checks" class="level2">
<h2 class="anchored" data-anchor-id="sanity-checks">Sanity checks</h2>
<p>Before interpreting recovery, the executable unit must pass these generator and data checks:</p>
<ol type="1">
<li><strong>Polar identity:</strong> numerical <span class="math inline">\(\dot r\)</span> and <span class="math inline">\(\dot\theta\)</span> computed from the analytic field match <span class="math inline">\(r(1-r^2)\)</span> and <span class="math inline">\(2\)</span> away from the origin.</li>
<li><strong>Radial direction:</strong> on the finest latent grid, <span class="math inline">\(r_{k+1}-r_k\ge-10^{-10}\)</span> for <span class="math inline">\(r_0&lt;1\)</span> and <span class="math inline">\(r_{k+1}-r_k\le10^{-10}\)</span> for <span class="math inline">\(r_0&gt;1\)</span>.</li>
<li><strong>Cycle check:</strong> a trajectory initialized at <span class="math inline">\(r_0=1\)</span> remains within <span class="math inline">\(10^{-8}\)</span> of unit radius over <span class="math inline">\([0,8]\)</span> under the tighter-solver diagnostic.</li>
<li><strong>Period check:</strong> from <span class="math inline">\(z_0=(1,0)\)</span>, integrate with RK4 step <span class="math inline">\(h=0.001\)</span>, detect the first negative-to-nonnegative crossing of <span class="math inline">\(y(t)\)</span> after <span class="math inline">\(t=0.1\)</span>, linearly interpolate within that step, and require agreement with <span class="math inline">\(\pi\)</span> to relative error below <span class="math inline">\(10^{-6}\)</span>.</li>
<li><strong>Split check:</strong> train, primary test, and extrapolation initial-condition records and seeds are disjoint and have the declared exact stratum counts.</li>
<li><strong>Noise check:</strong> empirical noise means and covariance over all generated observations are reported for each <span class="math inline">\(\sigma\)</span>; this is a diagnostic, not a requirement that every finite sample equal its population moment.</li>
<li><strong>Leakage check:</strong> feature scaling and regression use training trajectories only.</li>
<li><strong>Determinism check:</strong> two executions with the same manifest produce byte-identical tabular metrics and numerically identical arrays.</li>
</ol>
</section>
<section id="failure-cases" class="level2">
<h2 class="anchored" data-anchor-id="failure-cases">Failure cases</h2>
<p>The implementation must report, not hide, at least these failures:</p>
<ul>
<li>The cubic estimator fails to beat the linear baseline in the noiseless, finest-sampling condition. This indicates an implementation, derivative-estimation, or evaluation defect before it supports a scientific conclusion.</li>
<li>Coarse sampling and observation noise produce biased derivative targets, unstable coefficients, or divergent rollouts. The condition <span class="math inline">\((\Delta t,\sigma)=(0.10,0.05)\)</span> is an explicit stress condition and may fail.</li>
<li>The derivative-permutation negative control matches the unshuffled estimator. This suggests leakage, an insensitive metric, or a recovery task that does not use state–velocity correspondence.</li>
<li>Rollouts leave a radius of 3 or the numerical solver fails. Such runs are counted as failures and assigned infinite rollout error for ranking; their finite pre-failure horizon is also recorded.</li>
<li>A smoother erases the radial transient or creates apparently smooth rotation not supported by raw observations. Smoothed state error and field error must therefore be reported separately.</li>
<li>Good observation reconstruction coincides with poor field recovery. This is not resolved by selecting the visually better trajectory.</li>
</ul>
</section>
<section id="recovery-task" class="level2">
<h2 class="anchored" data-anchor-id="recovery-task">Recovery task</h2>
<p>Recovery is performed without supplying the analytic form or coefficients of <span class="math inline">\(f\)</span> to the estimator.</p>
<ol type="1">
<li><p>Smooth each observed coordinate independently with centered local-cubic least squares. NumPy computes the state and first-derivative filter coefficients by pseudoinverting the cubic design matrix on windows of 21, 11, and 5 points for <span class="math inline">\(\Delta t=0.025,0.05,0.10\)</span>. Only the common interior interval <span class="math inline">\(0.30\le t_k\le7.70\)</span> is retained; no padded edge output is fitted or scored.</p></li>
<li><p>Construct features in the exact raw order</p>
<p><span class="math display">\[
\phi(z)=[1,x,y,x^2,xy,y^2,x^3,x^2y,xy^2,y^3].
\]</span></p></li>
<li><p>Retain only smoothed training samples with <span class="math inline">\(0.30\le t\le2.0\)</span> for vector-field fitting, preventing the long near-cycle tail from dominating the radial transients. If there are <span class="math inline">\(n\)</span> retained rows, set <span class="math inline">\(\mu_j=n^{-1}\sum_i\phi_{ij}\)</span> and <span class="math inline">\(s_j=[n^{-1}\sum_i(\phi_{ij}-\mu_j)^2]^{1/2}\)</span> for <span class="math inline">\(j=1,\ldots,9\)</span>; a zero <span class="math inline">\(s_j\)</span> is a failed run. Define <span class="math inline">\(X_{i0}=1\)</span> and <span class="math inline">\(X_{ij}=(\phi_{ij}-\mu_j)/s_j\)</span>. Thus scaling uses population standard deviation (<code>ddof=0</code>) on training rows only.</p></li>
<li><p>For each velocity component <span class="math inline">\(v\)</span>, solve the deterministic ridge problem</p>
<p><span class="math display">\[
\hat b
=\arg\min_b
\left\{n^{-1}\|Xb-v\|_2^2+\lambda b^TPb\right\},
\qquad
P=\operatorname{diag}(0,1,\ldots,1),
\quad
\lambda=10^{-4},
\]</span></p>
<p>using a linear solve, not an explicit matrix inverse. Convert to raw coefficients by <span class="math inline">\(c_j=b_j/s_j\)</span> for <span class="math inline">\(j\ge1\)</span> and <span class="math inline">\(c_0=b_0-\sum_{j=1}^9b_j\mu_j/s_j\)</span>.</p></li>
<li><p>Integrate the recovered autonomous field for each held-out trajectory from the common grid-aligned start <span class="math inline">\(t=0.30\)</span> through <span class="math inline">\(t=8\)</span>.</p></li>
<li><p>Produce two rollout variants: <strong>oracle-initialized</strong>, starting at the known held-out <span class="math inline">\(z(0.30)\)</span> to isolate field recovery, and <strong>observation-initialized</strong>, starting at the smoothed estimate <span class="math inline">\(\hat z(0.30)\)</span> to measure end-to-end degradation.</p></li>
</ol>
<p>The recovered object is a vector-field estimate in the declared observation/latent coordinates. One fitted trajectory is not treated as the recovered field.</p>
</section>
<section id="candidate-analysis-methods" class="level2">
<h2 class="anchored" data-anchor-id="candidate-analysis-methods">Candidate analysis methods</h2>
<p>Only three bounded analyses are planned:</p>
<ol type="1">
<li><strong>Primary:</strong> cubic polynomial ridge regression on smoothed derivative estimates.</li>
<li><strong>Simpler baseline:</strong> linear ridge regression using the same smoothed states, derivative targets, penalty, feature scaling rule, and rollout procedure.</li>
<li><strong>Negative control:</strong> for each acquisition condition and noise replicate, pool the retained training rows, draw one permutation of row indices, and apply it jointly to the paired two-component derivative vectors while leaving states/features fixed. The scaler, ridge objective, solver, and evaluation are otherwise unchanged. This is a derivative-permutation control, not a permutation of observation times within each trajectory.</li>
</ol>
<p>No neural network, manifold learner, sparse-regression library, or broad hyperparameter search is included. The fixed cubic basis contains the true field but the estimator is not told which coefficients are nonzero; this makes the example a recovery and noise-sensitivity demonstration, not a model-class-discovery benchmark.</p>
</section>
<section id="evaluation" class="level2">
<h2 class="anchored" data-anchor-id="evaluation">Evaluation</h2>
<p>All primary metrics use held-out trajectories or the fixed evaluation grid in the same declared coordinates as the generator. Let <span class="math inline">\(\mathcal T_{\mathrm{state}}\)</span> be the condition-specific observation times in <span class="math inline">\([0.30,7.70]\)</span>, and let the common rollout grid be</p>
<p><span class="math display">\[
\mathcal T_{\mathrm{roll}}=\{0.30+0.10m:m=0,\ldots,77\}.
\]</span></p>
<ul>
<li><p><strong>Smoothed-state RMSE:</strong> for one trajectory,</p>
<p><span class="math display">\[
\operatorname{RMSE}_{z}
=\left[|\mathcal T_{\mathrm{state}}|^{-1}
\sum_{t\in\mathcal T_{\mathrm{state}}}
\|\hat z(t)-z(t)\|_2^2\right]^{1/2}.
\]</span></p></li>
<li><p><strong>Vector-field normalized RMSE:</strong></p>
<p><span class="math display">\[
\operatorname{NRMSE}_f
=
\sqrt{
\frac{\sum_{z\in\mathcal G}\|\hat f(z)-f(z)\|_2^2}
     {\sum_{z\in\mathcal G}\|f(z)\|_2^2}
},
\]</span></p>
<p>on the fixed grid <span class="math inline">\(\mathcal G\subset\mathcal D_{\mathrm{eval}}\)</span>.</p></li>
<li><p><strong>One-step state RMSE:</strong> for one trajectory, integrate <span class="math inline">\(\hat f\)</span> for that condition’s <span class="math inline">\(\Delta t\)</span> from each true state at retained <span class="math inline">\(t_k\)</span> with <span class="math inline">\(t_{k+1}\le7.70\)</span>, then take the root mean of squared Euclidean next-state errors.</p></li>
<li><p><strong>Rollout trajectory RMSE:</strong> use the same formula as <span class="math inline">\(\operatorname{RMSE}_z\)</span> on <span class="math inline">\(\mathcal T_{\mathrm{roll}}\)</span> for oracle- and observation-initialized rollouts beginning at <span class="math inline">\(t=0.30\)</span>.</p></li>
<li><p><strong>Radial error:</strong> on <span class="math inline">\(\mathcal T_{\mathrm{roll}}\)</span>, take the root mean of <span class="math inline">\([\hat r(t)-r(t)]^2\)</span>, reported separately because phase and radius errors have different interpretations for this oscillator.</p></li>
<li><p><strong>Coefficient error:</strong> if <span class="math inline">\(C\)</span> and <span class="math inline">\(\hat C\)</span> are the two-output raw coefficient matrices in the declared feature order, report <span class="math inline">\(\|\hat C-C\|_F/\|C\|_F\)</span>. This metric is valid here only because the generator and estimator share declared coordinates and basis.</p></li>
<li><p><strong>Failure rate:</strong> fraction of held-out rollouts that cross radius 3, terminate early, or produce nonfinite values.</p></li>
</ul>
<p>For each noise replicate, trajectory-level state, one-step, rollout, and radial errors are summarized by their median and interquartile range across the 40 primary test trajectories; failure rate is the fraction of those trajectories. Vector-field and coefficient errors yield one value per fitted model. A nonzero-noise condition is then summarized by the median and interquartile range of its ten replicate-level summaries. The noiseless condition reports its single fitted-model value and its trajectory median/interquartile range. Raw trajectory and replicate values remain available.</p>
<p>The preregistered primary success check is limited to the noiseless fine condition and the moderate condition <span class="math inline">\((\Delta t,\sigma)=(0.05,0.02)\)</span>. In the noiseless condition, the single cubic fit must have lower vector-field NRMSE and lower median-across-trajectories oracle-rollout RMSE than the linear baseline. In the moderate condition, the cubic estimator must have lower median-across-replicates vector-field NRMSE and oracle-rollout RMSE than the linear baseline. In both conditions, the derivative-permutation control must not outperform the unpermuted cubic estimator. The plan does not require every noisy or extrapolation condition to succeed. Exact metric values and all negative results must be reported; no threshold is retrofitted after inspection.</p>
<section id="observed-bounded-results" class="level3">
<h3 class="anchored" data-anchor-id="observed-bounded-results">Observed bounded results</h3>
<div class="callout callout-style-default callout-important callout-titled" title="Executed Result">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Executed Result
</div>
</div>
<div class="callout-body-container callout-body">
<p>These values are outputs of the deterministic simulator and fixed recovery pipeline under master seed <code>20260818</code>. They are empirical results relative to this implementation, not established properties of other systems.</p>
</div>
</div>
<p>The preregistered comparisons passed:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th>Model</th>
<th style="text-align: right;">Field NRMSE</th>
<th style="text-align: right;">Median oracle-rollout RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\Delta t=0.025\)</span>, <span class="math inline">\(\sigma=0\)</span></td>
<td>Cubic</td>
<td style="text-align: right;">0.00275</td>
<td style="text-align: right;">0.000829</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\Delta t=0.025\)</span>, <span class="math inline">\(\sigma=0\)</span></td>
<td>Affine</td>
<td style="text-align: right;">0.45370</td>
<td style="text-align: right;">0.23136</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\Delta t=0.025\)</span>, <span class="math inline">\(\sigma=0\)</span></td>
<td>Derivative permutation</td>
<td style="text-align: right;">1.05446</td>
<td style="text-align: right;">1.40472</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\Delta t=0.05\)</span>, <span class="math inline">\(\sigma=0.02\)</span></td>
<td>Cubic, median over 10 replicates</td>
<td style="text-align: right;">0.01315</td>
<td style="text-align: right;">0.00482</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\Delta t=0.05\)</span>, <span class="math inline">\(\sigma=0.02\)</span></td>
<td>Affine, median over 10 replicates</td>
<td style="text-align: right;">0.45331</td>
<td style="text-align: right;">0.22429</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\Delta t=0.05\)</span>, <span class="math inline">\(\sigma=0.02\)</span></td>
<td>Derivative permutation, median over 10 replicates</td>
<td style="text-align: right;">1.02738</td>
<td style="text-align: right;">1.41368</td>
</tr>
</tbody>
</table>
<p>Across the nine primary conditions, cubic median oracle-rollout RMSE increased from 0.000829 in the noiseless finest condition to 0.03406 at <span class="math inline">\((\Delta t,\sigma)=(0.10,0.05)\)</span>. The corresponding cubic field NRMSE increased from 0.00275 to 0.07477. This supports the planned qualitative sensitivity to sampling and noise without implying strict monotonicity in each replicate.</p>
<p>For the separate outer-radius stress test at <span class="math inline">\((0.05,0.02)\)</span>, the cubic median oracle-rollout RMSE was 0.00333, compared with 0.34546 for the affine baseline. This is simulator-specific extrapolation over the declared radius range, not general evidence of extrapolation robustness. No cubic or affine rollout crossed the failure radius; derivative-permutation rollouts failed in 783 of 2680 evaluated trajectory/model instances, which is retained as negative-control behavior rather than discarded.</p>
<p>The analytic-generator checks also passed: polar-identity residual <span class="math inline">\(1.33\times10^{-15}\)</span>, RK4-versus-analytic maximum Euclidean error <span class="math inline">\(1.33\times10^{-9}\)</span>, unit-cycle radial error <span class="math inline">\(1.11\times10^{-16}\)</span>, and relative period error <span class="math inline">\(9.43\times10^{-12}\)</span>.</p>
</section>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<p>In this executed run, when the state coordinates were directly observed and the true field lay in the fitted cubic function class, the transparent derivative-regression pipeline recovered the declared simulator’s local vector field and finite-time trajectories under the preregistered conditions. The comparison with the affine baseline isolated the value of the nonlinear terms within this simulator, while the stress conditions showed sensitivity to derivative estimation, sampling, and accumulated rollout error. These results remain specific to the declared generator, observation map, estimator class, and evaluation support.</p>
<p>A failed run under this contract would still be informative: the same metric decomposition would help diagnose whether failure began in state smoothing, derivative estimation, field fitting, or finite-time integration. This counterfactual diagnostic structure prevents one favorable visualization or reconstruction score from masking another failure.</p>
</section>
<section id="what-this-toy-model-does-not-establish" class="level2">
<h2 class="anchored" data-anchor-id="what-this-toy-model-does-not-establish">What this toy model does NOT establish</h2>
<p>This toy model does not establish that:</p>
<ul>
<li>real neural or behavioral data follow this oscillator or any autonomous ODE;</li>
<li>a low-dimensional visualization is a manifold or a complete state space;</li>
<li>low trajectory error identifies a unique mechanism or latent coordinate system;</li>
<li>the cubic estimator discovers the correct model class when that class is unknown;</li>
<li>smoothing-induced regularity is evidence of smooth true dynamics;</li>
<li>direct identity observations represent realistic sensors;</li>
<li>recovery inside <span class="math inline">\(\mathcal D_{\mathrm{eval}}\)</span> implies extrapolation outside it;</li>
<li>good one-step prediction guarantees accurate long-horizon flow recovery; or</li>
<li>a simulated attracting cycle validates a limit-cycle interpretation in observed data.</li>
</ul>
<p>Ground truth here is simulator-relative. It is known because it is declared, not because the same quantities would be observable in an experiment.</p>
</section>
<section id="extensions-to-real-data" class="level2">
<h2 class="anchored" data-anchor-id="extensions-to-real-data">Extensions to real data</h2>
<p>Any later real-data extension would first need a defensible state description, a nontrivial observation model, irregular or missing-data handling, uncertainty quantification, and held-out interventions or conditions. Model comparison should then include non-autonomous, stochastic, and simpler non-dynamical alternatives. None of those extensions is authorized by this object.</p>
</section>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">Reproducibility</h2>
<p>The executed implementation uses:</p>
<ul>
<li>master seed <code>20260818</code> and NumPy <code>Generator(PCG64(SeedSequence(words)))</code>. Initial-condition generators use words <code>[20260818, 1, split_code]</code> with <code>split_code</code> 1=train, 2=test, 3=extrapolation. For each split and replicate <span class="math inline">\(q=0,\ldots,9\)</span>, standard-normal noise on the finest <span class="math inline">\(\Delta t=0.025\)</span> grid uses <code>[20260818, 2, split_code, q]</code>; coarser schedules subsample the same noise realization, and <span class="math inline">\(\sigma=0.02\)</span> and <span class="math inline">\(0.05\)</span> scale the same standard-normal array. This pairs noise across sampling intervals and noise scales. Derivative-permutation controls use <code>[20260818, 3, dt_code, sigma_code, q]</code>, where <code>dt_code</code> is 25, 50, or 100 and <code>sigma_code</code> is 0, 20, or 50;</li>
<li>source target <code>toy-models/two-dimensional-autonomous-dynamics.py</code>;</li>
<li>generated artifact directory <code>toy-models/artifacts/two-dimensional-autonomous-dynamics/</code>;</li>
<li>required outputs <code>manifest.json</code>, <code>latent-trajectories.npz</code>, <code>observations.npz</code>, <code>metrics.csv</code>, <code>coefficients.csv</code>, and versioned <code>.png</code> figures;</li>
<li>bundled Python 3.12.13, NumPy 2.3.5, and Pillow 12.3.0; SciPy and Matplotlib were unavailable and were not installed. On this machine, the approved runtime interpreter was <code>/Users/bytedance/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3</code>; this host-specific path is not a portability claim, and another environment must match the versions recorded in <code>manifest.json</code>;</li>
<li>from the <code>toy-models/</code> directory, <code>/Users/bytedance/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3 two-dimensional-autonomous-dynamics.py --generate</code> regenerates every artifact, and <code>/Users/bytedance/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3 two-dimensional-autonomous-dynamics.py --verify</code> checks hashes, scientific diagnostics, and a deterministic temporary regeneration;</li>
<li>a CPU-only default using one process, no GPU, peak resident memory below 4 GB, a target full-run wall time below 15 minutes on a four-core laptop-class CPU, and a verification target below 5 minutes. Exceeding a target is reported rather than bypassed with unrecorded concurrency or approximation.</li>
</ul>
<p>The generated manifest records equations, parameters, sample counts, exact runtime versions, plan deviations, smoothing rules, feature order, ridge penalty, evaluation support, and SHA-256 hashes. The bounded artifact set is:</p>
<ul>
<li><code>manifest.json</code>;</li>
<li><code>latent-trajectories.npz</code>;</li>
<li><code>observations.npz</code>, containing paired finest-grid standard-normal arrays plus representative observations from which all declared conditions reconstruct by subsampling and scaling;</li>
<li><code>metrics.csv</code> with raw condition, replicate, split, model, unit, and metric records;</li>
<li><code>coefficients.csv</code>;</li>
<li><code>diagnostics.json</code>; and</li>
<li><code>summary.png</code>.</li>
</ul>
<p>Full deterministic regeneration and verification passed in the existing runtime. The implementation completed in about 33 seconds per generation on the current machine, within the declared resource target.</p>
<section id="planning-maturity-checklist" class="level3">
<h3 class="anchored" data-anchor-id="planning-maturity-checklist">Planning maturity checklist</h3>
<ul class="task-list">
<li><label><input type="checkbox" checked="">Exact 2D autonomous ground truth and parameters are fixed.</label></li>
<li><label><input type="checkbox" checked="">Initial-condition laws, time support, solver, sampling, and observation noise are fixed.</label></li>
<li><label><input type="checkbox" checked="">Generation, observation, recovery, baseline, and negative control are separate.</label></li>
<li><label><input type="checkbox" checked="">Held-out conditions and state, field, one-step, and rollout metrics are declared.</label></li>
<li><label><input type="checkbox" checked="">Seeds, artifact paths, diagnostics, and failure handling are specified.</label></li>
<li><label><input type="checkbox" checked="">Interpretation limits and the simulator-relative meaning of ground truth are explicit.</label></li>
<li><label><input type="checkbox" checked="">Executable generation, recovery, bounded artifacts, and deterministic verification are complete.</label></li>
<li><label><input type="checkbox" checked="">Independent Toy Model Red-Team technical review passed.</label></li>
<li><label><input type="checkbox" checked="">Independent implementation/result review passed after two bounded correction cycles.</label></li>
<li><label><input type="checkbox" checked="">The owner explicitly approved promotion from <code>L1/review</code> to <code>L1/stable</code> on 2026-08-19; the promotion does not broaden the interpretation limits above.</label></li>
</ul>


<!-- -->

</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/abelzheng\.github\.io\/latent-dynamics-geometry-public\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="preferred_color_scheme">
<input type="hidden" id="giscus-alt-theme" value="preferred_color_scheme">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "AbelZheng/latent-dynamics-geometry-public";
    script.dataset.repoId = "R_kgDOT-VBkw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOT-VBk84DDyEz";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "bottom";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Two-Dimensional Autonomous Dynamics: Generation and Recovery"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">object_type:</span><span class="co"> toy-model</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">maturity:</span><span class="co"> L1</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">status:</span><span class="co"> stable</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">domain:</span><span class="co"> [dynamics, system-identification]</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="an">tags:</span><span class="co"> [two-dimensional, autonomous-ode, vector-field-recovery, simulation]</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="an">prerequisites:</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/state.qmd</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/state-space.qmd</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/trajectory.qmd</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/initial-condition.qmd</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/vector-field.qmd</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/flow.qmd</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/math/first-order-autonomous-dynamical-system.qmd</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="an">related:</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/observation-model.qmd</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/observation-noise.qmd</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/latent-trajectory.qmd</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">- knowledge/concepts/limit-cycle.qmd</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="an">created:</span><span class="co"> 2026-08-18</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="an">updated:</span><span class="co"> 2026-08-19</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu"># Two-Dimensional Autonomous Dynamics: Generation and Recovery</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>This L1 object records both the reviewed implementation contract and its bounded executable realization. Its <span class="in">`stable`</span> status records owner-authorized acceptance after independent technical and implementation/result review. The generated results test the declared simulator and recovery pipeline; stable status does not validate a real system or turn recovery performance into mechanistic evidence.</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>**Assumed background:** elementary multivariable calculus and polar coordinates; basic probability and linear algebra; polynomial regression and ridge-regression basics; finite differences and smoothing; and elementary numerical integration. These external basics are not repository prerequisites.</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>Can a transparent cubic polynomial estimator recover a known nonlinear two-dimensional autonomous vector field and its held-out trajectories from directly observed, finitely sampled, noisy state coordinates, and when does it improve over a linear baseline?</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>The demonstration is deliberately narrow. It asks whether a method recovers one declared simulator under controlled sampling and noise, not whether an autonomous model is appropriate for a real system.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ground truth</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>Let $z(t)=(x(t),y(t))\in\mathbb R^2$ and define</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>\dot x=(\alpha-\beta r^2)x-\omega y,</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>\dot y=\omega x+(\alpha-\beta r^2)y,</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>where $r^2=x^2+y^2$, with fixed parameters</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>\alpha=1,</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>\beta=1,</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>\omega=2.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>In polar coordinates this field has</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>\dot r=r(1-r^2),</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>\dot\theta=2.</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>For $r_0&gt;0$, an analytic reference solution is</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>r(t)=\left<span class="co">[</span><span class="ot">1+(r_0^{-2}-1)e^{-2t}\right</span><span class="co">]</span>^{-1/2},</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>\theta(t)=\theta_0+2t.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>Thus the origin is a fixed point, every nonzero initial condition rotates counterclockwise, and radii below or above one approach the isolated periodic orbit $r=1$. These properties follow from the declared equations and serve as simulator checks; they are not inferred from generated plots.</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>The state space is $\mathbb R^2$. Primary training and evaluation are restricted to trajectories initialized with $0.35\le r_0\le1.65$. Field error is evaluated on the declared annulus</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>\mathcal D_{\mathrm{eval}}=<span class="sc">\{</span>(x,y):0.35\le\sqrt{x^2+y^2}\le1.65<span class="sc">\}</span>,</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>so conclusions do not extend automatically to the origin or to arbitrary radii.</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="fu">## Generative model</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>Generation and observation are separate steps.</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Draw an initial state $z_0=(r_0\cos\theta_0,r_0\sin\theta_0)$ from the distributions below.</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Solve the deterministic initial-value problem $\dot z=f(z)$ from $t=0$ to $t=8$.</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Evaluate the same continuous latent solution at the requested observation interval $\Delta t$.</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Generate direct observations</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>   $$</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>   y_k=z(t_k)+\varepsilon_k,</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>   \qquad</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>   \varepsilon_k\overset{\mathrm{iid}}\sim\mathcal N(0,\sigma^2I_2).</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>   $$</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>The identity observation map fixes the latent coordinate convention. Sampling interval and observation noise are manipulations of the measurement process; they do not alter $f$, its parameters, or the latent initial-condition law.</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a><span class="fu">## Parameters</span></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Component <span class="pp">|</span> Fixed plan <span class="pp">|</span></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ground-truth field <span class="pp">|</span> $f(x,y)=((1-r^2)x-2y,\;2x+(1-r^2)y)$ <span class="pp">|</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Integration interval <span class="pp">|</span> $t\in<span class="co">[</span><span class="ot">0,8</span><span class="co">]</span>$ <span class="pp">|</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Primary initial radii <span class="pp">|</span> exact half-split: $U<span class="co">[</span><span class="ot">0.35,0.75</span><span class="co">]</span>$ and $U<span class="co">[</span><span class="ot">1.25,1.65</span><span class="co">]</span>$ <span class="pp">|</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Initial angles <span class="pp">|</span> $U[0,2\pi)$ independently of radius <span class="pp">|</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Training / test trajectories <span class="pp">|</span> 64 / 40 independent initial conditions <span class="pp">|</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Sampling intervals <span class="pp">|</span> $\Delta t\in<span class="sc">\{</span>0.025,0.05,0.10<span class="sc">\}</span>$ <span class="pp">|</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Observation-noise scales <span class="pp">|</span> $\sigma\in<span class="sc">\{</span>0,0.02,0.05<span class="sc">\}</span>$ in state-coordinate units <span class="pp">|</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Noise replicates <span class="pp">|</span> 10 per nonzero-noise condition; one deterministic replicate when $\sigma=0$ <span class="pp">|</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Primary recovery basis <span class="pp">|</span> all monomials in $(x,y)$ of total degree at most three <span class="pp">|</span></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Baseline basis <span class="pp">|</span> constant plus degree-one terms only <span class="pp">|</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ridge penalty <span class="pp">|</span> $\lambda=10^{-4}$ after standardizing nonconstant feature columns on training data <span class="pp">|</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Smoothing windows <span class="pp">|</span> 21, 11, and 5 points for $\Delta t=0.025,0.05,0.10$, respectively; cubic Savitzky--Golay polynomial <span class="pp">|</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Evaluation grid <span class="pp">|</span> $\rho_i=0.35+i(1.30/26)$, $i=0,\ldots,26$; $\theta_j=2\pi j/64$, $j=0,\ldots,63$ <span class="pp">|</span></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>The training split contains exactly 32 initial radii from each interval; the primary test split contains exactly 20 from each. Angles are sampled independently. This exact stratification forces both splits to include trajectories approaching the cycle from both sides. Test initial conditions use independent seeds and are held out as entire trajectories.</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>For each sampling interval,</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>t_k=k\Delta t,</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>k=0,\ldots,8/\Delta t,</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>including both endpoints. The three conditions therefore contain 321, 161, and 81 observation times, respectively. The angular grid excludes the duplicated endpoint $2\pi$; both radial endpoints are included.</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="fu">## Simulation</span></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>The reviewed plan specified SciPy DOP853 for numerical generation. SciPy was not available in the existing approved runtime, and no dependency was installed. The executable therefore uses the exact analytic polar solution as the primary generator and checks it independently with a NumPy fixed-step fourth-order Runge--Kutta integrator using $h=0.005$. This is an explicit implementation realization, not a silent change to the ground-truth field, time support, sampling conditions, or evaluation contract.</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>The implementation generates latent trajectories once per initial condition and derives every sampling condition from the same continuous solution. Independent paired standard-normal draws are added only after sampling and scaled by the declared $\sigma$. Train and test arrays remain separate; no held-out time point enters feature scaling or regression fitting. The smoothing duration and every recovery hyperparameter remain fixed rather than selected on test results.</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>The executable source is <span class="in">`two-dimensional-autonomous-dynamics.py`</span>. It implements the centered local-cubic filters with NumPy pseudoinverses, the declared ridge objective with NumPy linear algebra, recovered rollouts with RK4, and a composite PNG with the already available Pillow library.</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="fu">## Visualization</span></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>The bounded composite diagnostic produces:</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>true phase portraits with inner and outer trajectories and the unit cycle;</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>true and recovered vector-field arrows on the same fixed evaluation grid, shown in separate panels rather than visually subtracting one from the other;</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>metric heat maps over $(\Delta t,\sigma)$ for cubic and affine oracle-rollout error; and</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>the preregistered primary comparisons plus the explicit derivative-permutation failure count.</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>Held-out trajectory-level errors, fitted coefficients, and all failure flags/horizons remain in <span class="in">`metrics.csv`</span>, <span class="in">`coefficients.csv`</span>, and <span class="in">`diagnostics.json`</span> rather than being compressed into the single bounded PNG.</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>Visualizations are diagnostics only. Numerical evaluation and negative controls determine whether recovery succeeded.</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a><span class="al">![Composite generator, vector-field, condition, and primary-comparison diagnostics](artifacts/two-dimensional-autonomous-dynamics/summary.png)</span></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="fu">## Expected behavior</span></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="LDG Design Expectation"}</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>The following expectations are falsifiable design predictions, not generated results.</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>In the noiseless, finest-sampling condition, cubic recovery should approximate the true polynomial field and outperform the misspecified linear baseline on field and rollout error.</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Increasing $\sigma$ or $\Delta t$ should worsen derivative estimation and downstream field recovery, although the trend need not be strictly monotone in every finite replicate.</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The linear baseline may approximate short local segments but should miss radius-dependent contraction and expansion across the full annulus.</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The derivative-permutation negative control should lose state-to-velocity structure and perform substantially worse than the unshuffled cubic fit.</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Long rollouts should amplify small field-estimation errors, so one-step error may remain low after trajectory error has become appreciable.</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>These expectations will not be enforced by retuning the simulator or estimator after results are seen. A violation is a result to diagnose.</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="fu">## Parameter manipulations</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>The primary bounded factorial design contains nine sampling/noise conditions:</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>\Delta t\in<span class="sc">\{</span>0.025,0.05,0.10<span class="sc">\}</span></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>\quad\times\quad</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>\sigma\in<span class="sc">\{</span>0,0.02,0.05<span class="sc">\}</span>.</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>Only the observation schedule and observation noise change. The latent field, integration interval, initial-condition distribution, data split sizes, smoother duration, feature basis, and ridge penalty remain fixed.</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>One labeled extrapolation stress test uses 16 additional held-out initial radii drawn from $U<span class="co">[</span><span class="ot">1.65,1.90</span><span class="co">]</span>$ with independent angles at $(\Delta t,\sigma)=(0.05,0.02)$. It is reported separately and is not part of the primary success criterion because it begins outside the field-evaluation annulus.</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a><span class="fu">## Sanity checks</span></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>Before interpreting recovery, the executable unit must pass these generator and data checks:</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Polar identity:** numerical $\dot r$ and $\dot\theta$ computed from the analytic field match $r(1-r^2)$ and $2$ away from the origin.</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Radial direction:** on the finest latent grid, $r_{k+1}-r_k\ge-10^{-10}$ for $r_0&lt;1$ and $r_{k+1}-r_k\le10^{-10}$ for $r_0&gt;1$.</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Cycle check:** a trajectory initialized at $r_0=1$ remains within $10^{-8}$ of unit radius over $<span class="co">[</span><span class="ot">0,8</span><span class="co">]</span>$ under the tighter-solver diagnostic.</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Period check:** from $z_0=(1,0)$, integrate with RK4 step $h=0.001$, detect the first negative-to-nonnegative crossing of $y(t)$ after $t=0.1$, linearly interpolate within that step, and require agreement with $\pi$ to relative error below $10^{-6}$.</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Split check:** train, primary test, and extrapolation initial-condition records and seeds are disjoint and have the declared exact stratum counts.</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Noise check:** empirical noise means and covariance over all generated observations are reported for each $\sigma$; this is a diagnostic, not a requirement that every finite sample equal its population moment.</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>**Leakage check:** feature scaling and regression use training trajectories only.</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>**Determinism check:** two executions with the same manifest produce byte-identical tabular metrics and numerically identical arrays.</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a><span class="fu">## Failure cases</span></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>The implementation must report, not hide, at least these failures:</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The cubic estimator fails to beat the linear baseline in the noiseless, finest-sampling condition. This indicates an implementation, derivative-estimation, or evaluation defect before it supports a scientific conclusion.</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Coarse sampling and observation noise produce biased derivative targets, unstable coefficients, or divergent rollouts. The condition $(\Delta t,\sigma)=(0.10,0.05)$ is an explicit stress condition and may fail.</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The derivative-permutation negative control matches the unshuffled estimator. This suggests leakage, an insensitive metric, or a recovery task that does not use state--velocity correspondence.</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rollouts leave a radius of 3 or the numerical solver fails. Such runs are counted as failures and assigned infinite rollout error for ranking; their finite pre-failure horizon is also recorded.</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A smoother erases the radial transient or creates apparently smooth rotation not supported by raw observations. Smoothed state error and field error must therefore be reported separately.</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Good observation reconstruction coincides with poor field recovery. This is not resolved by selecting the visually better trajectory.</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recovery task</span></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>Recovery is performed without supplying the analytic form or coefficients of $f$ to the estimator.</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Smooth each observed coordinate independently with centered local-cubic least squares. NumPy computes the state and first-derivative filter coefficients by pseudoinverting the cubic design matrix on windows of 21, 11, and 5 points for $\Delta t=0.025,0.05,0.10$. Only the common interior interval $0.30\le t_k\le7.70$ is retained; no padded edge output is fitted or scored.</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Construct features in the exact raw order</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>   $$</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>   \phi(z)=<span class="co">[</span><span class="ot">1,x,y,x^2,xy,y^2,x^3,x^2y,xy^2,y^3</span><span class="co">]</span>.</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>   $$</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Retain only smoothed training samples with $0.30\le t\le2.0$ for vector-field fitting, preventing the long near-cycle tail from dominating the radial transients. If there are $n$ retained rows, set $\mu_j=n^{-1}\sum_i\phi_{ij}$ and $s_j=[n^{-1}\sum_i(\phi_{ij}-\mu_j)^2]^{1/2}$ for $j=1,\ldots,9$; a zero $s_j$ is a failed run. Define $X_{i0}=1$ and $X_{ij}=(\phi_{ij}-\mu_j)/s_j$. Thus scaling uses population standard deviation (<span class="in">`ddof=0`</span>) on training rows only.</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>For each velocity component $v$, solve the deterministic ridge problem</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>   $$</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>   \hat b</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>   =\arg\min_b</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>   \left<span class="sc">\{</span>n^{-1}<span class="sc">\|</span>Xb-v<span class="sc">\|</span>_2^2+\lambda b^TPb\right<span class="sc">\}</span>,</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>   \qquad</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>   P=\operatorname{diag}(0,1,\ldots,1),</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>   \quad</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a>   \lambda=10^{-4},</span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>   $$</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>   using a linear solve, not an explicit matrix inverse. Convert to raw coefficients by $c_j=b_j/s_j$ for $j\ge1$ and $c_0=b_0-\sum_{j=1}^9b_j\mu_j/s_j$.</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Integrate the recovered autonomous field for each held-out trajectory from the common grid-aligned start $t=0.30$ through $t=8$.</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Produce two rollout variants: **oracle-initialized**, starting at the known held-out $z(0.30)$ to isolate field recovery, and **observation-initialized**, starting at the smoothed estimate $\hat z(0.30)$ to measure end-to-end degradation.</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>The recovered object is a vector-field estimate in the declared observation/latent coordinates. One fitted trajectory is not treated as the recovered field.</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a><span class="fu">## Candidate analysis methods</span></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>Only three bounded analyses are planned:</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Primary:** cubic polynomial ridge regression on smoothed derivative estimates.</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Simpler baseline:** linear ridge regression using the same smoothed states, derivative targets, penalty, feature scaling rule, and rollout procedure.</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Negative control:** for each acquisition condition and noise replicate, pool the retained training rows, draw one permutation of row indices, and apply it jointly to the paired two-component derivative vectors while leaving states/features fixed. The scaler, ridge objective, solver, and evaluation are otherwise unchanged. This is a derivative-permutation control, not a permutation of observation times within each trajectory.</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>No neural network, manifold learner, sparse-regression library, or broad hyperparameter search is included. The fixed cubic basis contains the true field but the estimator is not told which coefficients are nonzero; this makes the example a recovery and noise-sensitivity demonstration, not a model-class-discovery benchmark.</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a><span class="fu">## Evaluation</span></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>All primary metrics use held-out trajectories or the fixed evaluation grid in the same declared coordinates as the generator. Let $\mathcal T_{\mathrm{state}}$ be the condition-specific observation times in $<span class="co">[</span><span class="ot">0.30,7.70</span><span class="co">]</span>$, and let the common rollout grid be</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>\mathcal T_{\mathrm{roll}}=<span class="sc">\{</span>0.30+0.10m:m=0,\ldots,77<span class="sc">\}</span>.</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Smoothed-state RMSE:** for one trajectory,</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>  $$</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>  \operatorname{RMSE}_{z}</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>  =\left[|\mathcal T_{\mathrm{state}}|^{-1}</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>  \sum_{t\in\mathcal T_{\mathrm{state}}}</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>  <span class="sc">\|</span>\hat z(t)-z(t)<span class="sc">\|</span>_2^2\right]^{1/2}.</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>  $$</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Vector-field normalized RMSE:**</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>  $$</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>  \operatorname{NRMSE}_f</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>  =</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>  \sqrt{</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>  \frac{\sum_{z\in\mathcal G}<span class="sc">\|</span>\hat f(z)-f(z)<span class="sc">\|</span>_2^2}</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>       {\sum_{z\in\mathcal G}<span class="sc">\|</span>f(z)<span class="sc">\|</span>_2^2}</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>  },</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>  $$</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>  on the fixed grid $\mathcal G\subset\mathcal D_{\mathrm{eval}}$.</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**One-step state RMSE:** for one trajectory, integrate $\hat f$ for that condition's $\Delta t$ from each true state at retained $t_k$ with $t_{k+1}\le7.70$, then take the root mean of squared Euclidean next-state errors.</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Rollout trajectory RMSE:** use the same formula as $\operatorname{RMSE}_z$ on $\mathcal T_{\mathrm{roll}}$ for oracle- and observation-initialized rollouts beginning at $t=0.30$.</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Radial error:** on $\mathcal T_{\mathrm{roll}}$, take the root mean of $<span class="co">[</span><span class="ot">\hat r(t)-r(t)</span><span class="co">]</span>^2$, reported separately because phase and radius errors have different interpretations for this oscillator.</span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Coefficient error:** if $C$ and $\hat C$ are the two-output raw coefficient matrices in the declared feature order, report $<span class="sc">\|</span>\hat C-C<span class="sc">\|</span>_F/<span class="sc">\|</span>C<span class="sc">\|</span>_F$. This metric is valid here only because the generator and estimator share declared coordinates and basis.</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Failure rate:** fraction of held-out rollouts that cross radius 3, terminate early, or produce nonfinite values.</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a>For each noise replicate, trajectory-level state, one-step, rollout, and radial errors are summarized by their median and interquartile range across the 40 primary test trajectories; failure rate is the fraction of those trajectories. Vector-field and coefficient errors yield one value per fitted model. A nonzero-noise condition is then summarized by the median and interquartile range of its ten replicate-level summaries. The noiseless condition reports its single fitted-model value and its trajectory median/interquartile range. Raw trajectory and replicate values remain available.</span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>The preregistered primary success check is limited to the noiseless fine condition and the moderate condition $(\Delta t,\sigma)=(0.05,0.02)$. In the noiseless condition, the single cubic fit must have lower vector-field NRMSE and lower median-across-trajectories oracle-rollout RMSE than the linear baseline. In the moderate condition, the cubic estimator must have lower median-across-replicates vector-field NRMSE and oracle-rollout RMSE than the linear baseline. In both conditions, the derivative-permutation control must not outperform the unpermuted cubic estimator. The plan does not require every noisy or extrapolation condition to succeed. Exact metric values and all negative results must be reported; no threshold is retrofitted after inspection.</span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a><span class="fu">### Observed bounded results</span></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a>::: {.callout-important title="Executed Result"}</span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a>These values are outputs of the deterministic simulator and fixed recovery pipeline under master seed <span class="in">`20260818`</span>. They are empirical results relative to this implementation, not established properties of other systems.</span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>The preregistered comparisons passed:</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Condition <span class="pp">|</span> Model <span class="pp">|</span> Field NRMSE <span class="pp">|</span> Median oracle-rollout RMSE <span class="pp">|</span></span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---:|---:|</span></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\Delta t=0.025$, $\sigma=0$ <span class="pp">|</span> Cubic <span class="pp">|</span> 0.00275 <span class="pp">|</span> 0.000829 <span class="pp">|</span></span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\Delta t=0.025$, $\sigma=0$ <span class="pp">|</span> Affine <span class="pp">|</span> 0.45370 <span class="pp">|</span> 0.23136 <span class="pp">|</span></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\Delta t=0.025$, $\sigma=0$ <span class="pp">|</span> Derivative permutation <span class="pp">|</span> 1.05446 <span class="pp">|</span> 1.40472 <span class="pp">|</span></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\Delta t=0.05$, $\sigma=0.02$ <span class="pp">|</span> Cubic, median over 10 replicates <span class="pp">|</span> 0.01315 <span class="pp">|</span> 0.00482 <span class="pp">|</span></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\Delta t=0.05$, $\sigma=0.02$ <span class="pp">|</span> Affine, median over 10 replicates <span class="pp">|</span> 0.45331 <span class="pp">|</span> 0.22429 <span class="pp">|</span></span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\Delta t=0.05$, $\sigma=0.02$ <span class="pp">|</span> Derivative permutation, median over 10 replicates <span class="pp">|</span> 1.02738 <span class="pp">|</span> 1.41368 <span class="pp">|</span></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>Across the nine primary conditions, cubic median oracle-rollout RMSE increased from 0.000829 in the noiseless finest condition to 0.03406 at $(\Delta t,\sigma)=(0.10,0.05)$. The corresponding cubic field NRMSE increased from 0.00275 to 0.07477. This supports the planned qualitative sensitivity to sampling and noise without implying strict monotonicity in each replicate.</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a>For the separate outer-radius stress test at $(0.05,0.02)$, the cubic median oracle-rollout RMSE was 0.00333, compared with 0.34546 for the affine baseline. This is simulator-specific extrapolation over the declared radius range, not general evidence of extrapolation robustness. No cubic or affine rollout crossed the failure radius; derivative-permutation rollouts failed in 783 of 2680 evaluated trajectory/model instances, which is retained as negative-control behavior rather than discarded.</span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a>The analytic-generator checks also passed: polar-identity residual $1.33\times10^{-15}$, RK4-versus-analytic maximum Euclidean error $1.33\times10^{-9}$, unit-cycle radial error $1.11\times10^{-16}$, and relative period error $9.43\times10^{-12}$.</span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpretation</span></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a>In this executed run, when the state coordinates were directly observed and the true field lay in the fitted cubic function class, the transparent derivative-regression pipeline recovered the declared simulator's local vector field and finite-time trajectories under the preregistered conditions. The comparison with the affine baseline isolated the value of the nonlinear terms within this simulator, while the stress conditions showed sensitivity to derivative estimation, sampling, and accumulated rollout error. These results remain specific to the declared generator, observation map, estimator class, and evaluation support.</span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a>A failed run under this contract would still be informative: the same metric decomposition would help diagnose whether failure began in state smoothing, derivative estimation, field fitting, or finite-time integration. This counterfactual diagnostic structure prevents one favorable visualization or reconstruction score from masking another failure.</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a><span class="fu">## What this toy model does NOT establish</span></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a>This toy model does not establish that:</span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>real neural or behavioral data follow this oscillator or any autonomous ODE;</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a low-dimensional visualization is a manifold or a complete state space;</span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>low trajectory error identifies a unique mechanism or latent coordinate system;</span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>the cubic estimator discovers the correct model class when that class is unknown;</span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>smoothing-induced regularity is evidence of smooth true dynamics;</span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>direct identity observations represent realistic sensors;</span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>recovery inside $\mathcal D_{\mathrm{eval}}$ implies extrapolation outside it;</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>good one-step prediction guarantees accurate long-horizon flow recovery; or</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a simulated attracting cycle validates a limit-cycle interpretation in observed data.</span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>Ground truth here is simulator-relative. It is known because it is declared, not because the same quantities would be observable in an experiment.</span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a><span class="fu">## Extensions to real data</span></span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a>Any later real-data extension would first need a defensible state description, a nontrivial observation model, irregular or missing-data handling, uncertainty quantification, and held-out interventions or conditions. Model comparison should then include non-autonomous, stochastic, and simpler non-dynamical alternatives. None of those extensions is authorized by this object.</span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reproducibility</span></span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a>The executed implementation uses:</span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>master seed <span class="in">`20260818`</span> and NumPy <span class="in">`Generator(PCG64(SeedSequence(words)))`</span>. Initial-condition generators use words <span class="in">`[20260818, 1, split_code]`</span> with <span class="in">`split_code`</span> 1=train, 2=test, 3=extrapolation. For each split and replicate $q=0,\ldots,9$, standard-normal noise on the finest $\Delta t=0.025$ grid uses <span class="in">`[20260818, 2, split_code, q]`</span>; coarser schedules subsample the same noise realization, and $\sigma=0.02$ and $0.05$ scale the same standard-normal array. This pairs noise across sampling intervals and noise scales. Derivative-permutation controls use <span class="in">`[20260818, 3, dt_code, sigma_code, q]`</span>, where <span class="in">`dt_code`</span> is 25, 50, or 100 and <span class="in">`sigma_code`</span> is 0, 20, or 50;</span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>source target <span class="in">`toy-models/two-dimensional-autonomous-dynamics.py`</span>;</span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>generated artifact directory <span class="in">`toy-models/artifacts/two-dimensional-autonomous-dynamics/`</span>;</span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>required outputs <span class="in">`manifest.json`</span>, <span class="in">`latent-trajectories.npz`</span>, <span class="in">`observations.npz`</span>, <span class="in">`metrics.csv`</span>, <span class="in">`coefficients.csv`</span>, and versioned <span class="in">`.png`</span> figures;</span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>bundled Python 3.12.13, NumPy 2.3.5, and Pillow 12.3.0; SciPy and Matplotlib were unavailable and were not installed. On this machine, the approved runtime interpreter was <span class="in">`/Users/bytedance/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3`</span>; this host-specific path is not a portability claim, and another environment must match the versions recorded in <span class="in">`manifest.json`</span>;</span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>from the <span class="in">`toy-models/`</span> directory, <span class="in">`/Users/bytedance/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3 two-dimensional-autonomous-dynamics.py --generate`</span> regenerates every artifact, and <span class="in">`/Users/bytedance/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3 two-dimensional-autonomous-dynamics.py --verify`</span> checks hashes, scientific diagnostics, and a deterministic temporary regeneration;</span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a CPU-only default using one process, no GPU, peak resident memory below 4 GB, a target full-run wall time below 15 minutes on a four-core laptop-class CPU, and a verification target below 5 minutes. Exceeding a target is reported rather than bypassed with unrecorded concurrency or approximation.</span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a>The generated manifest records equations, parameters, sample counts, exact runtime versions, plan deviations, smoothing rules, feature order, ridge penalty, evaluation support, and SHA-256 hashes. The bounded artifact set is:</span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`manifest.json`</span>;</span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`latent-trajectories.npz`</span>;</span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`observations.npz`</span>, containing paired finest-grid standard-normal arrays plus representative observations from which all declared conditions reconstruct by subsampling and scaling;</span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`metrics.csv`</span> with raw condition, replicate, split, model, unit, and metric records;</span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`coefficients.csv`</span>;</span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`diagnostics.json`</span>; and</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`summary.png`</span>.</span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a>Full deterministic regeneration and verification passed in the existing runtime. The implementation completed in about 33 seconds per generation on the current machine, within the declared resource target.</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a><span class="fu">### Planning maturity checklist</span></span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Exact 2D autonomous ground truth and parameters are fixed.</span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Initial-condition laws, time support, solver, sampling, and observation noise are fixed.</span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Generation, observation, recovery, baseline, and negative control are separate.</span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Held-out conditions and state, field, one-step, and rollout metrics are declared.</span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Seeds, artifact paths, diagnostics, and failure handling are specified.</span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Interpretation limits and the simulator-relative meaning of ground truth are explicit.</span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Executable generation, recovery, bounded artifacts, and deterministic verification are complete.</span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Independent Toy Model Red-Team technical review passed.</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Independent implementation/result review passed after two bounded correction cycles.</span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> The owner explicitly approved promotion from <span class="in">`L1/review`</span> to <span class="in">`L1/stable`</span> on 2026-08-19; the promotion does not broaden the interpretation limits above.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>